/**
 * TTL (Tera Term Language) コマンド・キーワード定義
 */

/** TTLコマンドの定義 */
export interface TtlCommand {
  /** コマンド名（小文字） */
  readonly name: string;
  /** シグネチャ（書式） */
  readonly signature: string;
  /** 英語説明 */
  readonly description: string;
  /** 日本語説明 */
  readonly descriptionJa?: string;
  /** VSCodeスニペット形式の挿入テキスト */
  readonly snippet?: string;
}

/** TTLコマンド定義リスト */
export const TTL_COMMANDS: ReadonlyArray<TtlCommand> = [
  // ── 制御フロー ──────────────────────────────────────────────────────────────
  {
    name: 'if',
    signature: 'if <expression> <statement>\nif <expression> then\n  ...\nendif',
    description: 'Executes a statement, or a block of statements, if an expression is true (non-zero).',
    descriptionJa: '<expression> が真（0以外）ならば <statement> を実行',
    snippet: 'if ${1:expression} then\n\t$0\nendif',
  },
  {
    name: 'for',
    signature: 'for <intvar> <first> <last>\n  ...\nnext',
    description: 'Repeats the statements between "for" and "next" until the integer variable reaches <last>.',
    descriptionJa: 'for と next の間のコマンドを、整数変数 <intvar> が <last> に達するまで繰り返し',
    snippet: 'for ${1:i} ${2:1} ${3:10}\n\t$0\nnext',
  },
  {
    name: 'while',
    signature: 'while <expression>\n  ...\nendwhile',
    description: "Repeats the statements between 'while' and 'endwhile' while <expression> is non-zero.",
    descriptionJa: "while と endwhile の間のコマンドを、<expression> が 0 以外である限り繰り返し",
    snippet: 'while ${1:expression}\n\t$0\nendwhile',
  },
  {
    name: 'do',
    signature: 'do [ { while | until } <expression> ]\n  ...\nloop [ { while | until } <expression> ]',
    description: "Repeats the statements between 'do' and 'loop' according to condition.",
    descriptionJa: "do と loop の間のコマンドを、条件式に従って繰り返し",
    snippet: 'do\n\t$0\nloop while ${1:expression}',
  },
  {
    name: 'until',
    signature: 'until <expression>\n  ...\nenduntil',
    description: "Repeats the statements between 'until' and 'enduntil' while <expression> is zero.",
    descriptionJa: "until と enduntil の間のコマンドを、<expression> が 0 である限り繰り返し",
    snippet: 'until ${1:expression}\n\t$0\nenduntil',
  },
  {
    name: 'break',
    signature: 'break',
    description: 'Quits from "for", "while", "do-loop" or "until-enduntil" loop.',
    descriptionJa: 'for や while などのループから抜出',
  },
  {
    name: 'continue',
    signature: 'continue',
    description: 'Transfers control from inside a loop to the next iteration of that loop.',
    descriptionJa: 'for や while のループの内側から次の反復処理に移行',
  },
  {
    name: 'call',
    signature: 'call <label>',
    description: 'Calls a subroutine beginning with the <label> line.',
    descriptionJa: '<label> 行から始まるサブルーチンをコール',
    snippet: 'call ${1:label}',
  },
  {
    name: 'return',
    signature: 'return',
    description: 'Returns from a subroutine called by the "call" command.',
    descriptionJa: 'call コマンドで呼び出されたサブルーチンから復帰',
  },
  {
    name: 'goto',
    signature: 'goto <label>',
    description: 'Moves control to the next line of the <label>.',
    descriptionJa: '<label> 行の次の行へジャンプ',
    snippet: 'goto ${1:label}',
  },
  {
    name: 'end',
    signature: 'end',
    description: 'Ends the macro and closes MACRO.',
    descriptionJa: 'マクロと MACRO を終了',
  },
  {
    name: 'exit',
    signature: 'exit',
    description: 'Exits the include file and returns to the main file, or quits the macro if used in the main file.',
    descriptionJa: 'インクルードファイルから抜けてメインファイルに復帰、またはメインファイルでマクロを終了',
  },
  // ── 送受信 ───────────────────────────────────────────────────────────────────
  {
    name: 'send',
    signature: 'send <data1> [<data2> ...]',
    description: 'Causes Tera Term to send characters to the host.',
    descriptionJa: 'ホストへ文字列または数値を送信',
    snippet: "send '${1:text}'",
  },
  {
    name: 'sendln',
    signature: 'sendln [<data1> [<data2> ...]]',
    description: 'Causes Tera Term to send characters followed by a new-line character to the host.',
    descriptionJa: '文字列と改行をホストへ送信',
    snippet: "sendln '${1:text}'",
  },
  {
    name: 'sendbinary',
    signature: 'sendbinary <data1> [<data2> ...]',
    description: 'Sends data to the host without encoding conversion.',
    descriptionJa: 'バイナリデータをホストへ送信（エンコード変換なし）',
  },
  {
    name: 'sendbreak',
    signature: 'sendbreak',
    description: 'Raises the break interrupt to the host system on the serial console.',
    descriptionJa: 'シリアルコンソールでホスト側にブレーク割り込みを発生',
  },
  {
    name: 'sendbroadcast',
    signature: 'sendbroadcast <data1> [<data2> ...]',
    description: 'Causes Tera Term to broadcast characters to all terminals.',
    descriptionJa: 'すべての端末へブロードキャスト送信',
  },
  {
    name: 'sendfile',
    signature: 'sendfile <filename> <binary flag>',
    description: 'Causes Tera Term to send the file <filename> to the host.',
    descriptionJa: '<filename> で指定されたファイルをホストへ送信',
    snippet: "sendfile '${1:filename}' ${2:0}",
  },
  {
    name: 'sendkcode',
    signature: 'sendkcode <key code> <repeat count>',
    description: 'Causes Tera Term to perform a function defined for a key or key combination.',
    descriptionJa: 'キーコード <key code> に割り当てられた機能を Tera Term で実行',
  },
  {
    name: 'sendlnbroadcast',
    signature: 'sendlnbroadcast <data1> [<data2> ...]',
    description: 'Broadcasts characters followed by a new-line character to all terminals.',
    descriptionJa: '文字列と改行をすべての端末へブロードキャスト送信',
  },
  {
    name: 'sendlnmulticast',
    signature: 'sendlnmulticast <multicastname> <data1> [<data2> ...]',
    description: 'Multicasts characters followed by a new-line character to selected terminals.',
    descriptionJa: '文字列と改行を指定端末へマルチキャスト送信',
  },
  {
    name: 'sendmulticast',
    signature: 'sendmulticast <multicastname> <data1> [<data2> ...]',
    description: 'Sends characters to the multicast terminal specified by <multicastname>.',
    descriptionJa: '<multicastname> で指定した端末へマルチキャスト送信',
  },
  {
    name: 'sendtext',
    signature: 'sendtext <data1> [<data2> ...]',
    description: 'Sends characters to the host as text (without CR+LF conversion).',
    descriptionJa: 'テキストとしてホストへ文字を送信（CR+LF 変換なし）',
  },
  {
    name: 'dispstr',
    signature: 'dispstr <data1> [<data2> ...]',
    description: 'Causes Tera Term to display characters on the client terminal screen.',
    descriptionJa: '文字列または数値を端末画面に表示',
    snippet: "dispstr '${1:text}'",
  },
  // ── 受信・待機 ───────────────────────────────────────────────────────────────
  {
    name: 'wait',
    signature: 'wait <string1> [<string2> ...]',
    description: 'Pauses until one of the character strings is received from the host, or until timeout.',
    descriptionJa: '文字列のうち一つがホストから送られてくるか、タイムアウトするまで待機',
    snippet: "wait '${1:string}'",
  },
  {
    name: 'waitln',
    signature: 'waitln <string1> [<string2> ...]',
    description: 'Pauses until a line which contains one of the strings is received, or until timeout.',
    descriptionJa: '文字列のうち一つを含む行をホストから受信するか、タイムアウトするまで待機',
    snippet: "waitln '${1:string}'",
  },
  {
    name: 'waitn',
    signature: 'waitn <received byte count>',
    description: 'Pauses until the given number of bytes are received from the host, or until timeout.',
    descriptionJa: '指定バイト数以上のデータ受信まで待機',
  },
  {
    name: 'waitrecv',
    signature: 'waitrecv <sub-string> <len> <pos>',
    description: 'Pauses until a string satisfying a condition is received, or until timeout.',
    descriptionJa: '条件を満たす文字列がホストから送られてくるか、タイムアウトするまで待機',
  },
  {
    name: 'waitregex',
    signature: 'waitregex <regex1> [<regex2> ...]',
    description: 'Pauses until a line matching one of the regular expressions is received, or until timeout.',
    descriptionJa: '正規表現にマッチする行をホストから受信するか、タイムアウトするまで待機',
    snippet: "waitregex '${1:regex}'",
  },
  {
    name: 'wait4all',
    signature: 'wait4all <string1> [<string2> ...]',
    description: 'Pauses until one of the strings is received from all macro-linked terminals.',
    descriptionJa: 'マクロに接続されている全端末において、文字列のうち一つが送られてくるまで待機',
  },
  {
    name: 'waitevent',
    signature: 'waitevent <events>',
    description: 'Pauses until one of the events specified by <events> occurs.',
    descriptionJa: '<events> で指定されるイベントが発生するまで待機',
  },
  {
    name: 'recvln',
    signature: 'recvln',
    description: 'Retrieves a line of received characters and stores it in the system variable "inputstr".',
    descriptionJa: 'ホストから一行分を受信して inputstr に格納',
  },
  {
    name: 'recvfile',
    signature: 'recvfile <filename> <binary flag> <auto-stop wait time>',
    description: 'Writes the data received from the host to the specified file.',
    descriptionJa: 'ホストから受信したデータを <filename> で指定されたファイルに出力',
  },
  {
    name: 'flushrecv',
    signature: 'flushrecv',
    description: 'Discards all characters in the receive buffer.',
    descriptionJa: '受信バッファーのすべての文字を破棄',
  },
  // ── 接続管理 ─────────────────────────────────────────────────────────────────
  {
    name: 'connect',
    signature: 'connect <command line parameters>',
    description: "Runs Tera Term with the given parameters and links it to MACRO, or connects to the host if already linked.",
    descriptionJa: 'Tera Term を起動してホストに接続し MACRO とリンク',
    snippet: "connect '${1:host}'",
  },
  {
    name: 'cygconnect',
    signature: 'cygconnect [<command line parameters>]',
    description: 'Runs Tera Term connected to Cygwin and links it to MACRO.',
    descriptionJa: 'Cygwin に接続した Tera Term を起動して MACRO とリンク',
  },
  {
    name: 'disconnect',
    signature: 'disconnect [<confirm>]',
    description: 'Disconnects Tera Term from the host.',
    descriptionJa: 'Tera Term とホストの接続を切断',
  },
  {
    name: 'closett',
    signature: 'closett',
    description: 'Closes Tera Term and enters the unlinked state.',
    descriptionJa: 'Tera Term を終了し MACRO は非リンク状態に移行',
  },
  {
    name: 'unlink',
    signature: 'unlink',
    description: 'MACRO enters the unlinked state and can no longer control the Tera Term window.',
    descriptionJa: 'MACRO を非リンク状態にして Tera Term ウィンドウ制御を終了',
  },
  {
    name: 'testlink',
    signature: 'testlink',
    description: 'Tests the link and connection status. Sets "result" to 0 (no link), 1 (linked, not connected), or 2 (linked and connected).',
    descriptionJa: 'リンク・接続状態を result に格納（0=非リンク、1=リンク未接続、2=リンク接続）',
  },
  // ── 一時停止 ─────────────────────────────────────────────────────────────────
  {
    name: 'pause',
    signature: 'pause <time>',
    description: 'Pauses for <time> seconds.',
    descriptionJa: 'TTL 実行を <time> 秒間休止',
    snippet: 'pause ${1:1}',
  },
  {
    name: 'mpause',
    signature: 'mpause <time>',
    description: 'Pauses for <time> milliseconds.',
    descriptionJa: 'TTL 実行を <time> ミリ秒間休止',
    snippet: 'mpause ${1:500}',
  },
  // ── ダイアログ ───────────────────────────────────────────────────────────────
  {
    name: 'messagebox',
    signature: 'messagebox <message> <title> [<special>]',
    description: 'Displays a message box.',
    descriptionJa: 'メッセージボックスを表示',
    snippet: "messagebox '${1:message}' '${2:title}'",
  },
  {
    name: 'inputbox',
    signature: 'inputbox <message> <title> [<default> [<special>]]',
    description: 'Displays an input dialog box. The user input is stored in "inputstr".',
    descriptionJa: '入力ダイアログを表示して inputstr に格納',
    snippet: "inputbox '${1:message}' '${2:title}'",
  },
  {
    name: 'passwordbox',
    signature: 'passwordbox <message> <title> [<special>]',
    description: 'Displays a password input dialog. The input is masked and stored in "inputstr".',
    descriptionJa: 'パスワード入力ダイアログを表示して inputstr に格納',
    snippet: "passwordbox '${1:message}' '${2:title}'",
  },
  {
    name: 'yesnobox',
    signature: 'yesnobox <message> <title> [<special>]',
    description: 'Displays a Yes/No dialog. Sets "result" to 1 for Yes, 0 for No.',
    descriptionJa: 'Yes/No ダイアログを表示して result に格納（Yes=1, No=0）',
    snippet: "yesnobox '${1:message}' '${2:title}'",
  },
  {
    name: 'listbox',
    signature: 'listbox <message> <title> <string array> [<selected>] [<keyword parameter>...]',
    description: 'Displays a list box dialog. The selected index is stored in "result".',
    descriptionJa: 'リストボックスダイアログを表示して result に選択インデックスを格納',
    snippet: "listbox '${1:message}' '${2:title}' ${3:array}",
  },
  {
    name: 'statusbox',
    signature: 'statusbox <message> <title> [<special>]',
    description: 'Displays or updates the status dialog box.',
    descriptionJa: 'ステータスダイアログを表示または更新',
    snippet: "statusbox '${1:message}' '${2:title}'",
  },
  {
    name: 'closesbox',
    signature: 'closesbox',
    description: 'Closes the status dialog box opened by the "statusbox" command.',
    descriptionJa: 'statusbox で開いたステータスダイアログを閉じる',
  },
  {
    name: 'bringupbox',
    signature: 'bringupbox',
    description: 'Brings the status box to the top of the Z order.',
    descriptionJa: 'ステータスボックスを最前面に表示',
  },
  {
    name: 'dirnamebox',
    signature: 'dirnamebox <title> [<initialdir>]',
    description: 'Displays a folder browser dialog. The selected folder is stored in "inputstr".',
    descriptionJa: 'フォルダ選択ダイアログを表示して inputstr に格納',
    snippet: "dirnamebox '${1:title}'",
  },
  {
    name: 'filenamebox',
    signature: 'filenamebox <title> [<dialogtype> [<initialdir>]]',
    description: 'Displays a file open/save dialog. The selected filename is stored in "inputstr".',
    descriptionJa: 'ファイル選択ダイアログを表示して inputstr に格納',
    snippet: "filenamebox '${1:title}'",
  },
  {
    name: 'setdlgpos',
    signature: 'setdlgpos [<x> <y> [<position> [<offset x> <offset y>]]]',
    description: 'Changes the display position of dialog boxes shown by MACRO commands.',
    descriptionJa: 'マクロコマンドのダイアログ表示位置を変更',
  },
  // ── 文字列操作 ───────────────────────────────────────────────────────────────
  {
    name: 'sprintf',
    signature: 'sprintf <format> [<arg1> ...]',
    description: 'Formats the arguments according to the C printf format and stores the result in "inputstr".',
    descriptionJa: '引数を C printf 形式でフォーマットして inputstr に代入',
    snippet: "sprintf '${1:%s}' ${2:arg}",
  },
  {
    name: 'sprintf2',
    signature: 'sprintf2 <strvar> <format> [<arg1> ...]',
    description: 'Formats the arguments according to the C printf format and stores the result in <strvar>.',
    descriptionJa: '引数を C printf 形式でフォーマットして <strvar> に代入',
    snippet: "sprintf2 ${1:strvar} '${2:%s}' ${3:arg}",
  },
  {
    name: 'strconcat',
    signature: 'strconcat <strvar> <string>',
    description: 'Appends a copy of <string> to the end of the string variable <strvar>.',
    descriptionJa: '文字列変数 <strvar> の文字列値の最後に文字列 <string> を継ぎ足す',
    snippet: 'strconcat ${1:strvar} ${2:string}',
  },
  {
    name: 'strcopy',
    signature: 'strcopy <string> <pos> <len> <strvar>',
    description: 'Copies a substring of <string> (starting at <pos>, length <len>) to <strvar>.',
    descriptionJa: '文字列 <string> の <pos> 文字目から <len> 文字分を文字列変数 <strvar> にコピーする',
    snippet: 'strcopy ${1:string} ${2:1} ${3:len} ${4:strvar}',
  },
  {
    name: 'strlen',
    signature: 'strlen <string>',
    description: 'Returns the byte length of <string> in the system variable "result".',
    descriptionJa: '文字列 <string> の長さをシステム変数 result に格納する',
    snippet: 'strlen ${1:string}',
  },
  {
    name: 'strscan',
    signature: 'strscan <string> <substring>',
    description: 'Searches for <substring> in <string>. Returns its 1-origin position in "result", or 0 if not found.',
    descriptionJa: '文字列 <string> の中に部分文字列 <substring> が含まれているか調べる。位置(1オリジン)が result に格納される',
    snippet: 'strscan ${1:string} ${2:substring}',
  },
  {
    name: 'strmatch',
    signature: 'strmatch <target string> <regex>',
    description: 'Searches <target string> using a regular expression. Matched substrings are stored in groupmatchstr1-9.',
    descriptionJa: '<target string> を正規表現で検索する。マッチした部分が groupmatchstr1〜9 に格納される',
    snippet: "strmatch ${1:string} '${2:regex}'",
  },
  {
    name: 'strreplace',
    signature: 'strreplace <strvar> <index> <regex> <newstr>',
    description: 'Replaces a regex match in <strvar> starting at <index> with <newstr>.',
    descriptionJa: '文字列変数 <strvar> の <index> 位置から正規表現 <regex> を検索し、<newstr> に置き換える',
    snippet: "strreplace ${1:strvar} 1 '${2:regex}' '${3:newstr}'",
  },
  {
    name: 'strremove',
    signature: 'strremove <strvar> <index> <len>',
    description: 'Deletes <len> characters from <strvar> beginning at <index> (1-origin).',
    descriptionJa: '文字列変数 <strvar> の <index> 位置（1オリジン）から <len> 文字分を削除する',
    snippet: 'strremove ${1:strvar} ${2:1} ${3:len}',
  },
  {
    name: 'strinsert',
    signature: 'strinsert <strvar> <index> <string>',
    description: 'Inserts <string> at position <index> (1-origin) in <strvar>.',
    descriptionJa: '文字列変数 <strvar> の <index> 位置（1オリジン）に文字列 <string> を挿入する',
    snippet: 'strinsert ${1:strvar} ${2:1} ${3:string}',
  },
  {
    name: 'strcompare',
    signature: 'strcompare <string1> <string2>',
    description: 'Compares two strings. Sets "result" to 0 (equal), 1 (string1 > string2), or -1 (string1 < string2).',
    descriptionJa: '2つの文字列を比較し、結果をシステム変数 result に代入する（0: 等しい、1: 大、-1: 小）',
    snippet: 'strcompare ${1:string1} ${2:string2}',
  },
  {
    name: 'strsplit',
    signature: 'strsplit <strval> <separator> [<count>]',
    description: 'Splits <strval> by <separator> and stores parts in groupmatchstr1-9.',
    descriptionJa: '文字列 <strval> を区切り記号 <separator> で分割し、groupmatchstr1〜9 に返す',
    snippet: "strsplit ${1:strval} '${2:,}'",
  },
  {
    name: 'strjoin',
    signature: 'strjoin <strvar> <separator> [<count>]',
    description: 'Concatenates groupmatchstr1-9 with <separator> and stores the result in <strvar>.',
    descriptionJa: 'groupmatchstr1〜9 を区切り記号 <separator> で連結し、文字列変数 <strvar> に格納する',
    snippet: "strjoin ${1:strvar} '${2:,}'",
  },
  {
    name: 'strtrim',
    signature: 'strtrim <strvar> <trimchars>',
    description: 'Removes all leading and trailing occurrences of <trimchars> from <strvar>.',
    descriptionJa: '文字列変数 <strvar> の先頭と末尾から <trimchars> で指定された文字をすべて削除する',
    snippet: "strtrim ${1:strvar} ' '",
  },
  {
    name: 'strspecial',
    signature: 'strspecial <strvar> [<strval>]',
    description: 'Converts special character sequences (like \\n, \\t) in the string to actual characters.',
    descriptionJa: '渡された文字列に含まれる特殊文字を変換する',
    snippet: 'strspecial ${1:strvar}',
  },
  {
    name: 'tolower',
    signature: 'tolower <strvar> <string>',
    description: 'Converts all alphabetic characters in <string> to lower-case and returns the result in <strvar>.',
    descriptionJa: '<string> に含まれるアルファベットを全て小文字にし、<strvar> に代入する',
    snippet: 'tolower ${1:strvar} ${2:string}',
  },
  {
    name: 'toupper',
    signature: 'toupper <strvar> <string>',
    description: 'Converts all alphabetic characters in <string> to upper-case and returns the result in <strvar>.',
    descriptionJa: '<string> に含まれるアルファベットを全て大文字にし、<strvar> に代入する',
    snippet: 'toupper ${1:strvar} ${2:string}',
  },
  {
    name: 'int2str',
    signature: 'int2str <strvar> <integer value>',
    description: 'Converts <integer value> to its decimal string expression and stores it in <strvar>.',
    descriptionJa: '整数値 <integer value> を10進表現の文字列に変換して文字列型変数 <strvar> に代入する',
    snippet: 'int2str ${1:strvar} ${2:value}',
  },
  {
    name: 'str2int',
    signature: 'str2int <intvar> <string>',
    description: 'Converts the decimal or hexadecimal <string> to its numeric value and stores it in <intvar>.',
    descriptionJa: '文字列 <string> を整数値に変換し、整数変数 <intvar> に代入する',
    snippet: 'str2int ${1:intvar} ${2:string}',
  },
  {
    name: 'str2code',
    signature: 'str2code <intvar> <string>',
    description: 'Copies the ASCII code of the first character of <string> to <intvar>.',
    descriptionJa: '文字列 <string> が1文字の場合、その ASCII コードを整数変数 <intvar> に格納する',
    snippet: 'str2code ${1:intvar} ${2:string}',
  },
  {
    name: 'code2str',
    signature: 'code2str <strvar> <ASCII code>',
    description: 'Converts an ASCII code value to its character and stores it in <strvar>.',
    descriptionJa: '整数値 <ASCII code> に対応する文字を文字列変数 <strvar> に格納する',
    snippet: 'code2str ${1:strvar} ${2:code}',
  },
  {
    name: 'regexoption',
    signature: 'regexoption <option1> [<option2> ...]',
    description: 'Specifies the syntax, encoding, and options of the regular expression.',
    descriptionJa: 'strmatch, strreplace, waitregex で使用する正規表現の文法と文字エンコーディングを指定する',
  },
  // ── 数値演算 ─────────────────────────────────────────────────────────────────
  {
    name: 'random',
    signature: 'random <intvar> <max number>',
    description: 'Generates a random integer within the range 0..<max number> and assigns it to <intvar>.',
    descriptionJa: '0から<max number>までの整数の一様乱数を生成し、整数変数 <integer variable> へ代入する',
    snippet: 'random ${1:intvar} ${2:100}',
  },
  {
    name: 'rotateleft',
    signature: 'rotateleft <intvar> <intval> <count>',
    description: 'Rotates <intval> left by <count> bits and stores the result in <intvar>.',
    descriptionJa: '整数値 <intval> を左に <count> 桁ローテートした値を整数型変数 <intvar> にコピーする',
    snippet: 'rotateleft ${1:intvar} ${2:intval} ${3:count}',
  },
  {
    name: 'rotateright',
    signature: 'rotateright <intvar> <intval> <count>',
    description: 'Rotates <intval> right by <count> bits and stores the result in <intvar>.',
    descriptionJa: '整数値 <intval> を右に <count> 桁ローテートした値を整数型変数 <intvar> にコピーする',
    snippet: 'rotateright ${1:intvar} ${2:intval} ${3:count}',
  },
  {
    name: 'checksum8',
    signature: 'checksum8 <intvar> <string>',
    description: 'Calculates the 8-bit checksum of a string.',
    descriptionJa: '引数の文字列から加算サム(8bit)を計算する',
    snippet: 'checksum8 ${1:intvar} ${2:string}',
  },
  {
    name: 'checksum8file',
    signature: 'checksum8file <intvar> <filename>',
    description: 'Calculates the 8-bit checksum of a file.',
    descriptionJa: 'ファイルから加算サム(8bit)を計算する',
    snippet: "checksum8file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'checksum16',
    signature: 'checksum16 <intvar> <string>',
    description: 'Calculates the 16-bit checksum of a string.',
    descriptionJa: '引数の文字列から加算サム(16bit)を計算する',
    snippet: 'checksum16 ${1:intvar} ${2:string}',
  },
  {
    name: 'checksum16file',
    signature: 'checksum16file <intvar> <filename>',
    description: 'Calculates the 16-bit checksum of a file.',
    descriptionJa: 'ファイルから加算サム(16bit)を計算する',
    snippet: "checksum16file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'checksum32',
    signature: 'checksum32 <intvar> <string>',
    description: 'Calculates the 32-bit checksum of a string.',
    descriptionJa: '引数の文字列から加算サム(32bit)を計算する',
    snippet: 'checksum32 ${1:intvar} ${2:string}',
  },
  {
    name: 'checksum32file',
    signature: 'checksum32file <intvar> <filename>',
    description: 'Calculates the 32-bit checksum of a file.',
    descriptionJa: 'ファイルから加算サム(32bit)を計算する',
    snippet: "checksum32file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'crc16',
    signature: 'crc16 <intvar> <string>',
    description: 'Calculates the 16-bit CRC of a string.',
    descriptionJa: '引数の文字列からCRC(16bit)を計算する',
    snippet: 'crc16 ${1:intvar} ${2:string}',
  },
  {
    name: 'crc16file',
    signature: 'crc16file <intvar> <filename>',
    description: 'Calculates the 16-bit CRC of a file.',
    descriptionJa: 'ファイルからCRC(16bit)を計算する',
    snippet: "crc16file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'crc32',
    signature: 'crc32 <intvar> <string>',
    description: 'Calculates the 32-bit CRC of a string.',
    descriptionJa: '引数の文字列からCRC(32bit)を計算する',
    snippet: 'crc32 ${1:intvar} ${2:string}',
  },
  {
    name: 'crc32file',
    signature: 'crc32file <intvar> <filename>',
    description: 'Calculates the 32-bit CRC of a file.',
    descriptionJa: 'ファイルからCRC(32bit)を計算する',
    snippet: "crc32file ${1:intvar} '${2:filename}'",
  },
  // ── ファイル操作 ─────────────────────────────────────────────────────────────
  {
    name: 'fileopen',
    signature: 'fileopen <file handle> <filename> <append flag> [<readonly flag>]',
    description: 'Opens a file in binary mode. Sets "result" to 0 on success.',
    descriptionJa: 'ファイルをバイナリモードでオープンする。成功した場合、result に 0 が格納される',
    snippet: "fileopen ${1:fp} '${2:filename}' ${3:0}",
  },
  {
    name: 'fileclose',
    signature: 'fileclose <file handle>',
    description: 'Closes the file specified by <file handle>.',
    descriptionJa: 'ファイルハンドル <file handle> で指定されるファイルをクローズする',
    snippet: 'fileclose ${1:fp}',
  },
  {
    name: 'filecreate',
    signature: 'filecreate <file handle> <filename>',
    description: 'Creates and opens a new file.',
    descriptionJa: 'ファイル <filename> を新しく作成しオープンする',
    snippet: "filecreate ${1:fp} '${2:filename}'",
  },
  {
    name: 'fileread',
    signature: 'fileread <file handle> <read byte> <strvar>',
    description: 'Reads <read byte> bytes from the file into <strvar>.',
    descriptionJa: '<file handle> で指定されたファイルから指定したバイト数のデータを読み出す',
    snippet: 'fileread ${1:fp} ${2:512} ${3:strvar}',
  },
  {
    name: 'filereadln',
    signature: 'filereadln <file handle> <strvar>',
    description: 'Reads one line from the file into <strvar>.',
    descriptionJa: 'ファイルから一行読む。読み込まれた行は文字列変数 <strvar> に格納される',
    snippet: 'filereadln ${1:fp} ${2:strvar}',
  },
  {
    name: 'filewrite',
    signature: 'filewrite <file handle> <data>',
    description: 'Writes <data> to the file.',
    descriptionJa: 'ファイルハンドル <file handle> で指定されるファイルへ <data> を書き込む',
    snippet: 'filewrite ${1:fp} ${2:data}',
  },
  {
    name: 'filewriteln',
    signature: 'filewriteln <file handle> <data>',
    description: 'Writes <data> and CR+LF to the file.',
    descriptionJa: 'ファイルへ <data> と改行文字 (CR+LF) を書き込む',
    snippet: 'filewriteln ${1:fp} ${2:data}',
  },
  {
    name: 'fileseek',
    signature: 'fileseek <file handle> <offset> <origin>',
    description: 'Moves the file pointer. <origin>: 0=beginning, 1=current, 2=end.',
    descriptionJa: 'ファイルポインタを移動する。<origin>: 0=先頭, 1=現在位置, 2=末尾',
    snippet: 'fileseek ${1:fp} ${2:0} ${3:0}',
  },
  {
    name: 'fileseekback',
    signature: 'fileseekback <file handle>',
    description: 'Moves the file pointer to the position marked by "filemarkptr".',
    descriptionJa: '"filemarkptr" コマンドで保存したファイルポインタ位置に戻る',
    snippet: 'fileseekback ${1:fp}',
  },
  {
    name: 'filemarkptr',
    signature: 'filemarkptr <file handle>',
    description: 'Marks the current file pointer position.',
    descriptionJa: 'オープンされているファイルの現在のファイルポインタを保存する',
    snippet: 'filemarkptr ${1:fp}',
  },
  {
    name: 'filestat',
    signature: 'filestat <filename> <size> [<mtime>] [<drive>]',
    description: 'Obtains information about a file or directory.',
    descriptionJa: 'ファイルもしくはフォルダの統計情報を取得する',
    snippet: "filestat '${1:filename}' ${2:size}",
  },
  {
    name: 'filestrseek',
    signature: 'filestrseek <file handle> <string>',
    description: 'Searches for <string> in the file from the current position forward.',
    descriptionJa: 'ファイルから文字列 <string> を前方検索する',
    snippet: "filestrseek ${1:fp} '${2:string}'",
  },
  {
    name: 'filestrseek2',
    signature: 'filestrseek2 <file handle> <string>',
    description: 'Searches for <string> in the file from the current position backward.',
    descriptionJa: 'ファイルから文字列 <string> を後方検索する',
    snippet: "filestrseek2 ${1:fp} '${2:string}'",
  },
  {
    name: 'filetruncate',
    signature: 'filetruncate <filename> <size>',
    description: 'Changes the size of a file to <size> bytes.',
    descriptionJa: 'ファイル <filename> をサイズ <size> バイトの大きさに変更する',
  },
  {
    name: 'filecopy',
    signature: 'filecopy <file1> <file2>',
    description: 'Copies <file1> to <file2>. Sets "result" to 0 on success.',
    descriptionJa: 'ファイル <file1> をコピーし、ファイル <file2> を作成する',
    snippet: "filecopy '${1:file1}' '${2:file2}'",
  },
  {
    name: 'filerename',
    signature: 'filerename <file1> <file2>',
    description: 'Renames <file1> to <file2>. Sets "result" to 0 on success.',
    descriptionJa: 'ファイル <file1> を <file2> という名前に変更する',
    snippet: "filerename '${1:file1}' '${2:file2}'",
  },
  {
    name: 'filedelete',
    signature: 'filedelete <filename>',
    description: 'Deletes the specified file. Sets "result" to 0 on success.',
    descriptionJa: 'ファイル <filename> を削除する',
    snippet: "filedelete '${1:filename}'",
  },
  {
    name: 'filesearch',
    signature: 'filesearch <filename>',
    description: 'Searches for a file or folder. Sets "result" to 1 if found, 0 if not.',
    descriptionJa: 'ファイルまたはフォルダが存在するか調べる。存在する場合は result に 1 が返る',
    snippet: "filesearch '${1:filename}'",
  },
  {
    name: 'fileconcat',
    signature: 'fileconcat <file1> <file2>',
    description: 'Appends a copy of <file2> to the end of <file1>.',
    descriptionJa: 'ファイル <file2> の内容をファイル <file1> の最後に追加する',
    snippet: "fileconcat '${1:file1}' '${2:file2}'",
  },
  {
    name: 'filelock',
    signature: 'filelock <file handle> [<timeout>]',
    description: 'Locks the file for exclusive access.',
    descriptionJa: 'ファイル全体をロックし、他のプロセスからのアクセスを禁止する',
    snippet: 'filelock ${1:fp}',
  },
  {
    name: 'fileunlock',
    signature: 'fileunlock <file handle>',
    description: 'Unlocks the file.',
    descriptionJa: 'ファイル全体のロックを解除する',
    snippet: 'fileunlock ${1:fp}',
  },
  // ── フォルダ操作 ─────────────────────────────────────────────────────────────
  {
    name: 'foldercreate',
    signature: 'foldercreate <foldername>',
    description: 'Creates a new folder. Sets "result" to 0 on success.',
    descriptionJa: 'フォルダ <foldername> を新しく作成する',
    snippet: "foldercreate '${1:foldername}'",
  },
  {
    name: 'folderdelete',
    signature: 'folderdelete <foldername>',
    description: 'Deletes a folder. Sets "result" to 0 on success.',
    descriptionJa: 'フォルダ <foldername> を削除する',
    snippet: "folderdelete '${1:foldername}'",
  },
  {
    name: 'foldersearch',
    signature: 'foldersearch <foldername>',
    description: 'Searches for a folder. Sets "result" to 1 if found, 0 if not.',
    descriptionJa: 'フォルダが存在するか調べる。存在する場合は result に 1 が返る',
    snippet: "foldersearch '${1:foldername}'",
  },
  // ── ファイル検索 ─────────────────────────────────────────────────────────────
  {
    name: 'findfirst',
    signature: 'findfirst <dir handle> <file name> <strvar>',
    description: 'Searches for the first file matching the specified pattern.',
    descriptionJa: 'findfirst コマンドはファイル名パターンに合致する最初のファイルを探す',
    snippet: "findfirst ${1:handle} '${2:*.ttl}' ${3:strvar}",
  },
  {
    name: 'findnext',
    signature: 'findnext <dir handle> <strvar>',
    description: 'Searches for the next file matching the pattern set by "findfirst".',
    descriptionJa: '"findfirst" で設定したパターンに合致する次のファイルを探す',
    snippet: 'findnext ${1:handle} ${2:strvar}',
  },
  {
    name: 'findclose',
    signature: 'findclose <dir handle>',
    description: 'Closes the file search opened by "findfirst".',
    descriptionJa: '"findfirst" で開いたファイル検索を閉じる',
    snippet: 'findclose ${1:handle}',
  },
  // ── パス操作 ─────────────────────────────────────────────────────────────────
  {
    name: 'basename',
    signature: 'basename <strvar> <path>',
    description: 'Returns the trailing name component of a path.',
    descriptionJa: 'パス名 <path> からファイル名部分を <strvar> に格納する',
    snippet: 'basename ${1:strvar} ${2:path}',
  },
  {
    name: 'dirname',
    signature: 'dirname <strvar> <path>',
    description: 'Returns the directory component of a path.',
    descriptionJa: 'パス名 <path> のディレクトリ名部分を <strvar> に格納する',
    snippet: 'dirname ${1:strvar} ${2:path}',
  },
  {
    name: 'makepath',
    signature: 'makepath <strvar> <dir> <name>',
    description: 'Creates a full path name from a directory name and file name.',
    descriptionJa: 'ディレクトリ名 <dir> とファイル名 <name> からフルパス名を作成する',
    snippet: 'makepath ${1:strvar} ${2:dir} ${3:name}',
  },
  // ── 配列 ─────────────────────────────────────────────────────────────────────
  {
    name: 'intdim',
    signature: 'intdim <array> <size>',
    description: 'Defines an integer array with <size> elements.',
    descriptionJa: '<size> 個の要素を持つ整数配列型の変数 <array> を宣言する',
    snippet: 'intdim ${1:array} ${2:10}',
  },
  {
    name: 'strdim',
    signature: 'strdim <array> <size>',
    description: 'Defines a string array with <size> elements.',
    descriptionJa: '<size> 個の要素を持つ文字列配列型の変数 <array> を宣言する',
    snippet: 'strdim ${1:array} ${2:10}',
  },
  // ── 日時 ─────────────────────────────────────────────────────────────────────
  {
    name: 'getdate',
    signature: 'getdate <strvar> [<format> [<timezone>]]',
    description: 'Returns the current date in <strvar>. Default format is "YYYY-MM-DD".',
    descriptionJa: '現在の日付を文字列変数 <strvar> に格納する。デフォルト形式は "YYYY-MM-DD"',
    snippet: 'getdate ${1:strvar}',
  },
  {
    name: 'gettime',
    signature: 'gettime <strvar> [<format> [<timezone>]]',
    description: 'Returns the current time in <strvar>. Default format is "HH:MM:SS".',
    descriptionJa: '現在の時刻を文字列変数 <strvar> に格納する。デフォルト形式は "HH:MM:SS"',
    snippet: 'gettime ${1:strvar}',
  },
  {
    name: 'setdate',
    signature: 'setdate <date>',
    description: 'Sets the system date. The format of <date> should be "YYYY-MM-DD".',
    descriptionJa: 'システムの日付を変更する。<date> の形式は "YYYY-MM-DD"',
  },
  {
    name: 'settime',
    signature: 'settime <time>',
    description: 'Sets the system time. The format of <time> should be "HH:MM:SS".',
    descriptionJa: 'システムの時刻を変更する。<time> の形式は "HH:MM:SS"',
  },
  {
    name: 'uptime',
    signature: 'uptime <intvar>',
    description: 'Retrieves the number of milliseconds that have elapsed since Windows was started.',
    descriptionJa: 'Windows OS の稼働時間（ミリ秒）を <intvar> に格納する',
    snippet: 'uptime ${1:intvar}',
  },
  // ── 環境変数 ─────────────────────────────────────────────────────────────────
  {
    name: 'getenv',
    signature: 'getenv <envname> <strvar>',
    description: 'Retrieves the value of an environment variable and stores it in <strvar>.',
    descriptionJa: '環境変数 <envname> の値を文字列変数 <strvar> に格納する',
    snippet: "getenv '${1:PATH}' ${2:strvar}",
  },
  {
    name: 'setenv',
    signature: 'setenv <envname> <strval>',
    description: 'Sets an environment variable. Effective only within the macro.',
    descriptionJa: '環境変数 <envname> に <strval> をセットする（マクロ内でのみ有効）',
    snippet: "setenv '${1:VAR}' '${2:value}'",
  },
  {
    name: 'expandenv',
    signature: 'expandenv <strvar> [<strval>]',
    description: 'Expands environment variable strings (%VARNAME%) in the string.',
    descriptionJa: '文字列内の環境変数文字列(%variableName%)を展開する',
    snippet: 'expandenv ${1:strvar}',
  },
  // ── システム情報 ─────────────────────────────────────────────────────────────
  {
    name: 'getver',
    signature: 'getver <strvar> [<version>]',
    description: 'Returns the version of Tera Term in <strvar>.',
    descriptionJa: 'Tera Term のバージョンを <strvar> に格納する',
    snippet: 'getver ${1:strvar}',
  },
  {
    name: 'gethostname',
    signature: 'gethostname <strvar>',
    description: 'Retrieves the destination hostname or IP address and stores it in <strvar>.',
    descriptionJa: 'Tera Term が接続しているホスト名（IPアドレス）を文字列変数 <strvar> に格納する',
    snippet: 'gethostname ${1:strvar}',
  },
  {
    name: 'getipv4addr',
    signature: 'getipv4addr <string array> <intvar>',
    description: 'Retrieves the local IPv4 address list.',
    descriptionJa: 'ローカルの IPv4 アドレス一覧を取得する',
  },
  {
    name: 'getipv6addr',
    signature: 'getipv6addr <string array> <intvar>',
    description: 'Retrieves the local IPv6 address list.',
    descriptionJa: 'ローカルの IPv6 アドレス一覧を取得する',
  },
  {
    name: 'getmodemstatus',
    signature: 'getmodemstatus <intvar>',
    description: 'Retrieves the modem control-register values from the serial port.',
    descriptionJa: 'シリアルポートからモデム制御レジスタの値を読み出す',
    snippet: 'getmodemstatus ${1:intvar}',
  },
  {
    name: 'getspecialfolder',
    signature: 'getspecialfolder <strvar> <foldertype>',
    description: 'Stores a Windows special folder path in <strvar>.',
    descriptionJa: 'Windows の特殊フォルダを取得して <strvar> に格納する',
    snippet: 'getspecialfolder ${1:strvar} ${2:foldertype}',
  },
  {
    name: 'getttdir',
    signature: 'getttdir <strvar>',
    description: 'Stores the directory of ttpmacro.exe in <strvar>.',
    descriptionJa: 'ttpmacro.exe があるディレクトリを文字列変数 <strvar> に格納する',
    snippet: 'getttdir ${1:strvar}',
  },
  {
    name: 'getttpos',
    signature: 'getttpos <showflag> <window x> <window y> <window width> <window height> <client width> <client height>',
    description: 'Retrieves the position and size of the Tera Term window.',
    descriptionJa: 'Tera Term ウィンドウの位置とサイズを取得する',
    snippet: 'getttpos ${1:showflag} ${2:wx} ${3:wy} ${4:ww} ${5:wh} ${6:cw} ${7:ch}',
  },
  {
    name: 'gettitle',
    signature: 'gettitle <strvar>',
    description: 'Retrieves the title text of Tera Term and stores it in <strvar>.',
    descriptionJa: 'Tera Term のウィンドウタイトルを文字列変数 <strvar> に格納する',
    snippet: 'gettitle ${1:strvar}',
  },
  {
    name: 'settitle',
    signature: 'settitle <title>',
    description: 'Changes the title text of the Tera Term window.',
    descriptionJa: 'Tera Term のウィンドウタイトルを <title> に変更する',
    snippet: "settitle '${1:title}'",
  },
  // ── ディレクトリ ─────────────────────────────────────────────────────────────
  {
    name: 'getdir',
    signature: 'getdir <strvar>',
    description: 'Returns the current working directory for MACRO (not Tera Term).',
    descriptionJa: 'MACRO のカレントディレクトリを文字列変数 <strvar> に格納する',
    snippet: 'getdir ${1:strvar}',
  },
  {
    name: 'setdir',
    signature: 'setdir <dir>',
    description: 'Changes the current working directory for MACRO.',
    descriptionJa: 'MACRO のカレントディレクトリを <dir> に変更する',
    snippet: "setdir '${1:dir}'",
  },
  {
    name: 'changedir',
    signature: 'changedir <path>',
    description: "Changes the file transfer directory for Tera Term to <path>.",
    descriptionJa: 'Tera Term のファイル転送用ディレクトリを <path> に変更する',
    snippet: "changedir '${1:path}'",
  },
  // ── ウィンドウ表示 ───────────────────────────────────────────────────────────
  {
    name: 'show',
    signature: 'show <show flag>',
    description: 'Minimizes MACRO if <show flag> is 0, restores it if positive.',
    descriptionJa: '<show flag> が0の場合 MACRO を最小化する。0より大きい場合は元の大きさに戻して最前面に表示する',
    snippet: 'show ${1:1}',
  },
  {
    name: 'showtt',
    signature: 'showtt <show flag>',
    description: 'Controls the Tera Term VT window visibility: -1=hide, 0=minimize, positive=show.',
    descriptionJa: '<show flag> が-1なら VT ウィンドウを隠す。0なら最小化する。0より大きいなら表示する',
    snippet: 'showtt ${1:1}',
  },
  {
    name: 'clearscreen',
    signature: 'clearscreen <int>',
    description: 'Erases the screen: 0=VT screen, 1=VT screen+scroll buffer, 2=TEK screen.',
    descriptionJa: '<int> が0の場合 VT ウィンドウの画面を消去。1の場合はスクロールバッファーも消去',
    snippet: 'clearscreen ${1:0}',
  },
  {
    name: 'beep',
    signature: 'beep [<sound type>]',
    description: 'Makes a beep sound. Sound types: 0=simple, 1=asterisk, 2=exclamation, 3=critical, 4=question, 5=default.',
    descriptionJa: 'WAVE 形式のサウンドを再生する',
    snippet: 'beep ${1:0}',
  },
  // ── ログ ─────────────────────────────────────────────────────────────────────
  {
    name: 'logopen',
    signature: 'logopen <filename> <binary flag> <append flag> [<plain text flag> [<timestamp flag>]]',
    description: 'Opens a log file and starts logging received characters.',
    descriptionJa: 'ログファイルを開いて受信文字のログ採取を開始する',
    snippet: "logopen '${1:logfile.log}' 0 0",
  },
  {
    name: 'logclose',
    signature: 'logclose',
    description: 'Closes the log file and stops logging.',
    descriptionJa: 'ログファイルを閉じてログ採取を停止する',
  },
  {
    name: 'logpause',
    signature: 'logpause',
    description: 'Pauses logging. Characters received while paused are discarded.',
    descriptionJa: 'ログ採取を一時中断する。中断中に受信された文字はログファイルに書き込まれない',
  },
  {
    name: 'logstart',
    signature: 'logstart',
    description: 'Restarts logging after "logpause".',
    descriptionJa: '"logpause" で中断したログ採取を再開する',
  },
  {
    name: 'logwrite',
    signature: 'logwrite <string>',
    description: 'Appends a string to the Tera Term log file.',
    descriptionJa: '文字列 <string> を Tera Term のログファイルに追加して書き込む',
    snippet: "logwrite '${1:string}'",
  },
  {
    name: 'loginfo',
    signature: 'loginfo <strvar>',
    description: 'Retrieves the current log filename into <strvar>. Sets "result" to -1 if not logging.',
    descriptionJa: 'ログを取得している場合、strvar にログファイル名が格納される。ログ取得していない場合は result に -1 が格納される',
    snippet: 'loginfo ${1:strvar}',
  },
  {
    name: 'logrotate',
    signature: "logrotate 'size' '<size>'\nlogrotate 'rotate' <count>\nlogrotate 'halt'",
    description: 'Configures log rotation.',
    descriptionJa: 'ログローテーションの設定を行う',
  },
  {
    name: 'logautoclosemode',
    signature: 'logautoclosemode <flag>',
    description: 'When <flag> is 1, automatically closes the log file when the macro finishes.',
    descriptionJa: '<flag> の値が1の場合、マクロ終了時に自動的にログ採取を停止する',
    snippet: 'logautoclosemode ${1:1}',
  },
  // ── パスワード管理 ───────────────────────────────────────────────────────────
  {
    name: 'setpassword',
    signature: 'setpassword <filename> <password name> <password>',
    description: 'Stores an encrypted password in a password file.',
    descriptionJa: 'パスワードファイル <filename> にパスワードを暗号化して保存する',
  },
  {
    name: 'getpassword',
    signature: 'getpassword <filename> <password name> <password var>',
    description: 'Retrieves and decrypts a password from a password file.',
    descriptionJa: 'パスワードファイルからパスワードを読みだして復号化する',
  },
  {
    name: 'delpassword',
    signature: 'delpassword <filename> <password name>',
    description: 'Deletes a password from a password file.',
    descriptionJa: 'パスワードファイルからパスワードを削除する',
  },
  {
    name: 'ispassword',
    signature: 'ispassword <filename> <password name>',
    description: 'Checks if a password exists in a password file.',
    descriptionJa: 'パスワードファイルにパスワードが存在するか調べる',
  },
  {
    name: 'setpassword2',
    signature: 'setpassword2 <filename> <password name> <password> <encrypt str>',
    description: 'Stores a password encrypted with a user-provided key.',
    descriptionJa: 'ユーザー指定のキーで暗号化したパスワードをパスワードファイルに保存する',
  },
  {
    name: 'getpassword2',
    signature: 'getpassword2 <filename> <password name> <password var> <encrypt str>',
    description: 'Retrieves and decrypts a password using a user-provided key.',
    descriptionJa: 'ユーザー指定のキーでパスワードを復号化して取得する',
  },
  {
    name: 'delpassword2',
    signature: 'delpassword2 <filename> <password name>',
    description: 'Deletes a password from a password file created by setpassword2.',
    descriptionJa: 'setpassword2 で作成されたパスワードファイルからパスワードを削除する',
  },
  {
    name: 'ispassword2',
    signature: 'ispassword2 <filename> <password name>',
    description: 'Checks if a password created by setpassword2 exists.',
    descriptionJa: 'setpassword2 で作成されたパスワードファイルにパスワードが存在するか調べる',
  },
  // ── ファイル転送プロトコル ───────────────────────────────────────────────────
  {
    name: 'bplusrecv',
    signature: 'bplusrecv',
    description: 'Receives a file from the host with the B-Plus protocol.',
    descriptionJa: 'B-Plus プロトコルでファイルを受信する',
  },
  {
    name: 'bplussend',
    signature: 'bplussend <filename>',
    description: 'Sends a file to the host with the B-Plus protocol.',
    descriptionJa: 'ファイル <filename> を B-Plus プロトコルで送信する',
    snippet: "bplussend '${1:filename}'",
  },
  {
    name: 'quickvanrecv',
    signature: 'quickvanrecv',
    description: 'Receives a file from the host with the Quick-VAN protocol.',
    descriptionJa: 'Quick-VAN プロトコルでファイルを受信する',
  },
  {
    name: 'quickvansend',
    signature: 'quickvansend <filename>',
    description: 'Sends a file to the host with the Quick-VAN protocol.',
    descriptionJa: 'ファイル <filename> を Quick-VAN プロトコルで送信する',
    snippet: "quickvansend '${1:filename}'",
  },
  {
    name: 'kmtrecv',
    signature: 'kmtrecv',
    description: 'Receives a file from the host with the Kermit protocol.',
    descriptionJa: 'Kermit プロトコルでファイルを受信する',
  },
  {
    name: 'kmtsend',
    signature: 'kmtsend <filename>',
    description: 'Sends a file to the host with the Kermit protocol.',
    descriptionJa: 'ファイル <filename> を Kermit プロトコルで送信する',
    snippet: "kmtsend '${1:filename}'",
  },
  {
    name: 'kmtget',
    signature: 'kmtget <filename>',
    description: 'Gets a file from the host using the Kermit Get command.',
    descriptionJa: 'ファイル <filename> を Kermit Get コマンドを使用してホストから受信する',
    snippet: "kmtget '${1:filename}'",
  },
  {
    name: 'kmtfinish',
    signature: 'kmtfinish',
    description: 'Pauses until the end of the Kermit Finish command.',
    descriptionJa: 'Kermit Finish コマンドが終了するまで次のコマンドは実行されない',
  },
  {
    name: 'xmodemrecv',
    signature: 'xmodemrecv <filename> <binary flag> <option>',
    description: 'Receives a file from the host with the XMODEM protocol.',
    descriptionJa: 'XMODEM プロトコルでファイル <filename> を受信する',
  },
  {
    name: 'xmodemsend',
    signature: 'xmodemsend <filename> <option>',
    description: 'Sends a file to the host with the XMODEM protocol.',
    descriptionJa: 'XMODEM プロトコルでファイル <filename> を送信する',
    snippet: "xmodemsend '${1:filename}' ${2:0}",
  },
  {
    name: 'ymodemrecv',
    signature: 'ymodemrecv',
    description: 'Receives a file from the host with the YMODEM protocol.',
    descriptionJa: 'YMODEM プロトコルでファイルを受信する',
  },
  {
    name: 'ymodemsend',
    signature: 'ymodemsend <filename>',
    description: 'Sends a file to the host with the YMODEM protocol.',
    descriptionJa: 'ファイル <filename> を YMODEM プロトコルで送信する',
    snippet: "ymodemsend '${1:filename}'",
  },
  {
    name: 'zmodemrecv',
    signature: 'zmodemrecv',
    description: 'Receives a file from the host with the ZMODEM protocol.',
    descriptionJa: 'ZMODEM プロトコルでファイルを受信する',
  },
  {
    name: 'zmodemsend',
    signature: 'zmodemsend <filename> <binary flag>',
    description: 'Sends a file to the host with the ZMODEM protocol.',
    descriptionJa: 'ファイル <filename> を ZMODEM プロトコルで送信する',
    snippet: "zmodemsend '${1:filename}' ${2:0}",
  },
  {
    name: 'scprecv',
    signature: 'scprecv <remote filename> [<local filename>]',
    description: 'Receives a file from the host with the SCP protocol.',
    descriptionJa: 'ファイル <remote filename> を SCP プロトコルで受信する',
    snippet: "scprecv '${1:remote filename}'",
  },
  {
    name: 'scpsend',
    signature: 'scpsend <filename> [<destination filename>]',
    description: 'Sends a file to the host with the SCP protocol.',
    descriptionJa: 'ファイル <filename> を SCP プロトコルで送信する',
    snippet: "scpsend '${1:filename}'",
  },
  // ── シリアル通信設定 ─────────────────────────────────────────────────────────
  {
    name: 'setbaud',
    signature: 'setbaud <value>',
    description: 'Changes the baud rate of the serial port.',
    descriptionJa: 'シリアルポートのボーレートを <value> bps に変更する',
    snippet: 'setbaud ${1:9600}',
  },
  {
    name: 'setspeed',
    signature: 'setspeed <value>',
    description: 'Changes the speed of the serial port.',
    descriptionJa: 'シリアルポートのスピードを <value> bps に変更する',
    snippet: 'setspeed ${1:9600}',
  },
  {
    name: 'setflowctrl',
    signature: 'setflowctrl <value>',
    description: 'Changes the flow control setting.',
    descriptionJa: 'フロー制御の設定を変更する',
    snippet: 'setflowctrl ${1:0}',
  },
  {
    name: 'setdtr',
    signature: 'setdtr <flag>',
    description: 'Sets or clears the DTR signal. Only effective for serial connections with no flow control.',
    descriptionJa: '接続がシリアル接続でフロー制御が none の場合に DTR 信号を制御する',
    snippet: 'setdtr ${1:1}',
  },
  {
    name: 'setrts',
    signature: 'setrts <flag>',
    description: 'Sets or clears the RTS signal. Only effective for serial connections with no flow control.',
    descriptionJa: '接続がシリアル接続でフロー制御が none の場合に RTS 信号を制御する',
    snippet: 'setrts ${1:1}',
  },
  {
    name: 'setserialdelaychar',
    signature: 'setserialdelaychar <delay>',
    description: 'Changes the inter-character delay for serial transmission in milliseconds.',
    descriptionJa: 'シリアルポートの送信待ち時間（1文字ごと）を <delay> [ms] に変更する',
    snippet: 'setserialdelaychar ${1:10}',
  },
  {
    name: 'setserialdelayline',
    signature: 'setserialdelayline <delay>',
    description: 'Changes the inter-line delay for serial transmission in milliseconds.',
    descriptionJa: 'シリアルポートの送信待ち時間（1行ごと）を <delay> [ms] に変更する',
    snippet: 'setserialdelayline ${1:100}',
  },
  // ── その他通信設定 ───────────────────────────────────────────────────────────
  {
    name: 'setsync',
    signature: 'setsync <sync flag>',
    description: 'Enters synchronous communication mode if <sync flag> is non-zero.',
    descriptionJa: '<sync flag> が0以外ならば同期通信モードに入る',
    snippet: 'setsync ${1:1}',
  },
  {
    name: 'setecho',
    signature: 'setecho <echo flag>',
    description: 'Turns local echo on (non-zero) or off (zero).',
    descriptionJa: '<echo flag> が0以外ならローカルエコーは on になる',
    snippet: 'setecho ${1:1}',
  },
  {
    name: 'enablekeyb',
    signature: 'enablekeyb <flag>',
    description: 'Enables (1) or disables (0) keyboard input.',
    descriptionJa: '<flag> の値が1の場合は許可、0の場合はキーボード入力を禁止する',
    snippet: 'enablekeyb ${1:1}',
  },
  {
    name: 'setmulticastname',
    signature: 'setmulticastname <multicastname>',
    description: 'Sets the multicast name of this terminal.',
    descriptionJa: '自身の端末に対して <multicastname> を識別子として設定する',
    snippet: "setmulticastname '${1:name}'",
  },
  // ── その他 ───────────────────────────────────────────────────────────────────
  {
    name: 'include',
    signature: "include '<include file name>'",
    description: 'Loads and executes the specified macro file.',
    descriptionJa: '引数に指定したマクロファイルを読み込み、マクロ実行を行う',
    snippet: "include '${1:filename.ttl}'",
  },
  {
    name: 'ifdefined',
    signature: 'ifdefined <var>',
    description: 'Sets "result" to the type of <var>: 0=undefined, 1=integer, 2=string, 3=int array, 4=string array.',
    descriptionJa: '<var> の型を表す値をシステム変数 result に格納する',
    snippet: 'ifdefined ${1:var}',
  },
  {
    name: 'exec',
    signature: 'exec <command line> [<show> [<wait> [<current directory>]]]',
    description: 'Runs an application specified by the command line.',
    descriptionJa: 'コマンドライン文字列 <command line> に従い、アプリケーションを起動する',
    snippet: "exec '${1:command}'",
  },
  {
    name: 'execcmnd',
    signature: 'execcmnd <statement>',
    description: 'Executes a TTL statement expressed by the string <statement>.',
    descriptionJa: '文字列 <statement> が表現する TTL コマンドを実行する',
    snippet: "execcmnd '${1:sendln \"hello\"}'",
  },
  {
    name: 'callmenu',
    signature: 'callmenu <menu ID>',
    description: 'Executes the menu item specified by <menu ID>.',
    descriptionJa: '<menu ID> で指定されたメニューを実行する',
    snippet: 'callmenu ${1:50280}',
  },
  {
    name: 'loadkeymap',
    signature: 'loadkeymap <filename>',
    description: 'Causes Tera Term to load a keyboard setup file.',
    descriptionJa: 'キーボード設定ファイル <filename> を Tera Term に読み込ませる',
    snippet: "loadkeymap '${1:keyboard.cnf}'",
  },
  {
    name: 'restoresetup',
    signature: 'restoresetup <filename>',
    description: 'Causes Tera Term to load a setup file.',
    descriptionJa: 'Tera Term 設定ファイル <filename> を Tera Term に読み込ませる',
    snippet: "restoresetup '${1:teraterm.ini}'",
  },
  {
    name: 'setdebug',
    signature: 'setdebug <flag>',
    description: 'Sets the debug flag of Tera Term.',
    descriptionJa: 'Tera Term のデバッグモードを設定する',
    snippet: 'setdebug ${1:1}',
  },
  {
    name: 'setexitcode',
    signature: 'setexitcode <exit code>',
    description: 'Sets the exit code of MACRO.',
    descriptionJa: 'MACRO の終了コードを設定する',
    snippet: 'setexitcode ${1:0}',
  },
  {
    name: 'setfileattr',
    signature: 'setfileattr <filename> <attributes>',
    description: 'Sets the file attributes.',
    descriptionJa: 'ファイルの属性を設定する',
  },
  {
    name: 'getfileattr',
    signature: 'getfileattr <filename>',
    description: 'Gets the file attributes. Stores the result in "result".',
    descriptionJa: 'ファイルの属性を取得する',
    snippet: "getfileattr '${1:filename}'",
  },
  {
    name: 'clipb2var',
    signature: 'clipb2var <strvar> [<offset>]',
    description: 'Copies text data from clipboard to <strvar>.',
    descriptionJa: 'クリップボードのテキストデータを <strvar> へ代入する',
    snippet: 'clipb2var ${1:strvar}',
  },
  {
    name: 'var2clipb',
    signature: 'var2clipb <string>',
    description: 'Copies <string> to the clipboard.',
    descriptionJa: '<string> をクリップボードにコピーする',
    snippet: 'var2clipb ${1:string}',
  },
] satisfies ReadonlyArray<TtlCommand>;

/**
 * コマンド名（小文字）からコマンド定義への参照マップ
 *
 * @remarks 補完・ホバーでの高速参照に使用
 */
export const TTL_COMMANDS_MAP: ReadonlyMap<string, TtlCommand> = new Map(
  TTL_COMMANDS.map(command => [command.name.toLowerCase(), command])
);

/**
 * 制御フロー構造キーワード
 *
 * @remarks コマンドデータがない純粋な構文キーワード
 */
export const TTL_STRUCTURAL_KEYWORDS = [
  'if', 'then', 'else', 'elseif', 'endif',
  'for', 'next',
  'while', 'endwhile',
  'do', 'loop',
  'until', 'enduntil',
  'break', 'continue',
  'call', 'return',
  'end', 'goto',
] as const satisfies ReadonlyArray<string>;

/**
 * システム変数
 *
 * @remarks コマンド実行結果や入力値を保持する定義済み変数
 */
export const TTL_SYSTEM_VARIABLES = [
  'result',
  'inputstr',
  'matchstr',
  'groupmatchstr1', 'groupmatchstr2', 'groupmatchstr3',
  'groupmatchstr4', 'groupmatchstr5', 'groupmatchstr6',
  'groupmatchstr7', 'groupmatchstr8', 'groupmatchstr9',
  'param1', 'param2', 'param3', 'param4', 'param5',
  'param6', 'param7', 'param8', 'param9',
  'params', 'paramcnt',
  'timeout', 'mtimeout',
] as const satisfies ReadonlyArray<string>;
