/**
 * TTL (Tera Term Language) コマンド・キーワード定義
 */

/** TTLコマンドの定義 */
export interface TtlCommand {
  /** コマンド名（小文字） */
  readonly name: string;
  /** シグネチャ（書式） */
  readonly signature: string;
  /** 英語説明 */
  readonly description: string;
  /** 日本語説明 */
  readonly descriptionJa?: string;
  /** 戻り値・関連システム変数の説明（英語） */
  readonly returns?: string;
  /** 戻り値・関連システム変数の説明（日本語） */
  readonly returnsJa?: string;
  /** VSCodeスニペット形式の挿入テキスト */
  readonly snippet?: string;
}

/**
 * ドキュメントヘッダ用スニペットの定義
 *
 * @remarks
 * 他言語の `///` ドキュメントコメントのように、`///` をトリガとして
 * `;` ベースの定型ヘッダを挿入するためのスニペット。TTL の行コメントは
 * `;` のみのため、入力した `///` は本文（`body`）で置換される。
 */
export interface TtlDocHeaderSnippet {
  /** 補完リストでの表示名 */
  readonly label: string;
  /** 補完候補の詳細（種別の補足） */
  readonly detail: string;
  /** 補完候補のドキュメント説明 */
  readonly documentation: string;
  /** VSCodeスニペット形式の挿入本文（`;` ベース） */
  readonly body: string;
}

/** TTLコマンド定義リスト */
export const TTL_COMMANDS: ReadonlyArray<TtlCommand> = [
  // ── 制御フロー ──────────────────────────────────────────────────────────────
  {
    name: 'if',
    signature: 'if <expression> <statement>\nif <expression> then\n  ...\nendif',
    description: 'Executes a statement, or a block of statements, if an expression is true (non-zero).',
    descriptionJa: '<expression> が真（0以外）ならば <statement> を実行',
    snippet: 'if ${1:expression} then\n\t$0\nendif',
  },
  {
    name: 'for',
    signature: 'for <intvar> <first> <last>\n  ...\nnext',
    description: 'Repeats the statements between "for" and "next" until the integer variable reaches <last>.',
    descriptionJa: 'for と next の間のコマンドを、整数変数 <intvar> が <last> に達するまで繰り返し',
    snippet: 'for ${1:i} ${2:1} ${3:10}\n\t$0\nnext',
  },
  {
    name: 'while',
    signature: 'while <expression>\n  ...\nendwhile',
    description: "Repeats the statements between 'while' and 'endwhile' while <expression> is non-zero.",
    descriptionJa: "while と endwhile の間のコマンドを、<expression> が 0 以外である限り繰り返し",
    snippet: 'while ${1:expression}\n\t$0\nendwhile',
  },
  {
    name: 'do',
    signature: 'do [ { while | until } <expression> ]\n  ...\nloop [ { while | until } <expression> ]',
    description: "Repeats the statements between 'do' and 'loop' according to condition.",
    descriptionJa: "do と loop の間のコマンドを、条件式に従って繰り返し",
    snippet: 'do\n\t$0\nloop while ${1:expression}',
  },
  {
    name: 'until',
    signature: 'until <expression>\n  ...\nenduntil',
    description: "Repeats the statements between 'until' and 'enduntil' while <expression> is zero.",
    descriptionJa: "until と enduntil の間のコマンドを、<expression> が 0 である限り繰り返し",
    snippet: 'until ${1:expression}\n\t$0\nenduntil',
  },
  {
    name: 'break',
    signature: 'break',
    description: 'Quits from "for", "while", "do-loop" or "until-enduntil" loop.',
    descriptionJa: 'for や while などのループから抜出',
  },
  {
    name: 'continue',
    signature: 'continue',
    description: 'Transfers control from inside a loop to the next iteration of that loop.',
    descriptionJa: 'for や while のループの内側から次の反復処理に移行',
  },
  {
    name: 'call',
    signature: 'call <label>',
    description: 'Calls a subroutine beginning with the <label> line.',
    descriptionJa: '<label> 行から始まるサブルーチンをコール',
    snippet: 'call ${1:label}',
  },
  {
    name: 'return',
    signature: 'return',
    description: 'Returns from a subroutine called by the "call" command.',
    descriptionJa: 'call コマンドで呼び出されたサブルーチンから復帰',
  },
  {
    name: 'goto',
    signature: 'goto <label>',
    description: 'Moves control to the next line of the <label>.',
    descriptionJa: '<label> 行の次の行へジャンプ',
    snippet: 'goto ${1:label}',
  },
  {
    name: 'end',
    signature: 'end',
    description: 'Ends the macro and closes MACRO.',
    descriptionJa: 'マクロと MACRO を終了',
  },
  {
    name: 'exit',
    signature: 'exit',
    description: 'Exits the include file and returns to the main file, or quits the macro if used in the main file.',
    descriptionJa: 'インクルードファイルから抜けてメインファイルに復帰、またはメインファイルでマクロを終了',
  },
  // ── 送受信 ───────────────────────────────────────────────────────────────────
  {
    name: 'send',
    signature: 'send <data1> [<data2> ...]',
    description: 'Causes Tera Term to send characters to the host.',
    descriptionJa: 'ホストへ文字列または数値を送信',
    snippet: "send '${1:text}'",
  },
  {
    name: 'sendln',
    signature: 'sendln [<data1> [<data2> ...]]',
    description: 'Causes Tera Term to send characters followed by a new-line character to the host.',
    descriptionJa: '文字列と改行をホストへ送信',
    snippet: "sendln '${1:text}'",
  },
  {
    name: 'sendbinary',
    signature: 'sendbinary <data1> [<data2> ...]',
    description: 'Sends data to the host without encoding conversion.',
    descriptionJa: 'バイナリデータをホストへ送信（エンコード変換なし）',
  },
  {
    name: 'sendbreak',
    signature: 'sendbreak',
    description: 'Raises the break interrupt to the host system on the serial console.',
    descriptionJa: 'シリアルコンソールでホスト側にブレーク割り込みを発生',
  },
  {
    name: 'sendbroadcast',
    signature: 'sendbroadcast <data1> [<data2> ...]',
    description: 'Causes Tera Term to broadcast characters to all terminals.',
    descriptionJa: 'すべての端末へブロードキャスト送信',
  },
  {
    name: 'sendfile',
    signature: 'sendfile <filename> <binary flag>',
    description: 'Causes Tera Term to send the file <filename> to the host.',
    descriptionJa: '<filename> で指定されたファイルをホストへ送信',
    snippet: "sendfile '${1:filename}' ${2:0}",
  },
  {
    name: 'sendkcode',
    signature: 'sendkcode <key code> <repeat count>',
    description: 'Causes Tera Term to perform a function defined for a key or key combination.',
    descriptionJa: 'キーコード <key code> に割り当てられた機能を Tera Term で実行',
  },
  {
    name: 'sendlnbroadcast',
    signature: 'sendlnbroadcast <data1> [<data2> ...]',
    description: 'Broadcasts characters followed by a new-line character to all terminals.',
    descriptionJa: '文字列と改行をすべての端末へブロードキャスト送信',
  },
  {
    name: 'sendlnmulticast',
    signature: 'sendlnmulticast <multicastname> <data1> [<data2> ...]',
    description: 'Multicasts characters followed by a new-line character to selected terminals.',
    descriptionJa: '文字列と改行を指定端末へマルチキャスト送信',
  },
  {
    name: 'sendmulticast',
    signature: 'sendmulticast <multicastname> <data1> [<data2> ...]',
    description: 'Sends characters to the multicast terminal specified by <multicastname>.',
    descriptionJa: '<multicastname> で指定した端末へマルチキャスト送信',
  },
  {
    name: 'sendtext',
    signature: 'sendtext <data1> [<data2> ...]',
    description: 'Sends characters to the host as text (without CR+LF conversion).',
    descriptionJa: 'テキストとしてホストへ文字を送信（CR+LF 変換なし）',
  },
  {
    name: 'dispstr',
    signature: 'dispstr <data1> [<data2> ...]',
    description: 'Causes Tera Term to display characters on the client terminal screen.',
    descriptionJa: '文字列または数値を端末画面に表示',
    snippet: "dispstr '${1:text}'",
  },
  // ── 受信・待機 ───────────────────────────────────────────────────────────────
  {
    name: 'wait',
    signature: 'wait <string1> [<string2> ...]',
    description: 'Pauses until one of the character strings is received from the host, or until timeout.',
    descriptionJa: '文字列のうち一つがホストから送られてくるか、タイムアウトするまで待機',
    returnsJa: '`result` … タイムアウトで 0、`<stringN>` を受信で n（1〜10）。タイムアウトは `timeout`/`mtimeout` で制御。',
    returns: '`result` … 0 on timeout, or n (1–10) when `<stringN>` is received. The timeout is controlled by `timeout`/`mtimeout`.',
    snippet: "wait '${1:string}'",
  },
  {
    name: 'waitln',
    signature: 'waitln <string1> [<string2> ...]',
    description: 'Pauses until a line which contains one of the strings is received, or until timeout.',
    descriptionJa: '文字列のうち一つを含む行をホストから受信するか、タイムアウトするまで待機',
    returnsJa: '受信した行を `inputstr` に格納。`result` … タイムアウトで 0、`<stringN>` を含む行を受信で n（1〜10）。',
    returns: 'Stores the received line in `inputstr`. `result` … 0 on timeout, or n (1–10) when a line containing `<stringN>` is received.',
    snippet: "waitln '${1:string}'",
  },
  {
    name: 'waitn',
    signature: 'waitn <received byte count>',
    description: 'Pauses until the given number of bytes are received from the host, or until timeout.',
    descriptionJa: '指定バイト数以上のデータ受信まで待機',
    returnsJa: '指定バイト数を受信すると `inputstr` に格納し `result` に 1（指定が 511 を超える場合は先頭 511 バイトのみ格納）、1文字も受信せずにタイムアウトで 0。',
    returns: 'On receiving the given number of bytes, stores them in `inputstr` and sets `result` to 1 (if the count exceeds 511, only the first 511 bytes are stored); 0 on timeout with no data received.',
  },
  {
    name: 'waitrecv',
    signature: 'waitrecv <sub-string> <len> <pos>',
    description: 'Pauses until a string satisfying a condition is received, or until timeout.',
    descriptionJa: '条件を満たす文字列がホストから送られてくるか、タイムアウトするまで待機',
    returnsJa: '条件を満たす文字列を受信すると `inputstr` に格納。`result` … 1=受信成功, 0=タイムアウト, -1=受信したが長さが `<len>` 未満。',
    returns: 'On a matching string, stores it in `inputstr`. `result` … 1=received, 0=timeout, -1=received but shorter than `<len>` due to timeout.',
  },
  {
    name: 'waitregex',
    signature: 'waitregex <regex1> [<regex2> ...]',
    description: 'Pauses until a line matching one of the regular expressions is received, or until timeout.',
    descriptionJa: '正規表現にマッチする行をホストから受信するか、タイムアウトするまで待機',
    returnsJa: '`result` … タイムアウトで 0、マッチで n（1〜10）。`inputstr` に受信行、`matchstr` に最初のマッチ、`groupmatchstr1`〜`groupmatchstr9` にグループマッチ結果。',
    returns: '`result` … 0 on timeout, or n (1–10) on match. `inputstr` holds the received line, `matchstr` the first match, and `groupmatchstr1`–`groupmatchstr9` the captured groups.',
    snippet: "waitregex '${1:regex}'",
  },
  {
    name: 'wait4all',
    signature: 'wait4all <string1> [<string2> ...]',
    description: 'Pauses until one of the strings is received from all macro-linked terminals.',
    descriptionJa: 'マクロに接続されている全端末において、文字列のうち一つが送られてくるまで待機',
    returnsJa: '`result` … タイムアウトで 0、`<stringN>` を受信で n（1〜10）。タイムアウトは `timeout`/`mtimeout` で制御。',
    returns: '`result` … 0 on timeout, or n (1–10) when `<stringN>` is received. The timeout is controlled by `timeout`/`mtimeout`.',
  },
  {
    name: 'waitevent',
    signature: 'waitevent <events>',
    description: 'Pauses until one of the events specified by <events> occurs.',
    descriptionJa: '<events> で指定されるイベントが発生するまで待機',
    returnsJa: '`result` … 発生したイベント識別子（1=timeout, 2=unlink, 4=disconnection, 8=connection）。',
    returns: '`result` … the identifier of the event that occurred (1=timeout, 2=unlink, 4=disconnection, 8=connection).',
  },
  {
    name: 'recvln',
    signature: 'recvln',
    description: 'Retrieves a line of received characters and stores it in the system variable "inputstr".',
    descriptionJa: 'ホストから一行分を受信して inputstr に格納',
    returnsJa: '受信した 1 行を `inputstr` に格納。`result` … 1 行受信で 1、それ以外（タイムアウト等）で 0。',
    returns: 'Stores the received line in `inputstr`. `result` … set to 1 when a line is received, 0 otherwise (e.g. timeout).',
  },
  {
    name: 'recvfile',
    signature: 'recvfile <filename> <binary flag> <auto-stop wait time>',
    description: 'Writes the data received from the host to the specified file.',
    descriptionJa: 'ホストから受信したデータを <filename> で指定されたファイルに出力',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'flushrecv',
    signature: 'flushrecv',
    description: 'Discards all characters in the receive buffer.',
    descriptionJa: '受信バッファーのすべての文字を破棄',
  },
  // ── 接続管理 ─────────────────────────────────────────────────────────────────
  {
    name: 'connect',
    signature: 'connect <command line parameters>',
    description: "Runs Tera Term with the given parameters and links it to MACRO, or connects to the host if already linked.",
    descriptionJa: 'Tera Term を起動してホストに接続し MACRO とリンク',
    returnsJa: '`result` … 0=Tera Term とリンクなし, 1=リンク済みだが未接続, 2=リンク・接続済み。',
    returns: '`result` … 0=not linked to Tera Term, 1=linked but not connected, 2=linked and connected.',
    snippet: "connect '${1:host}'",
  },
  {
    name: 'cygconnect',
    signature: 'cygconnect [<command line parameters>]',
    description: 'Runs Tera Term connected to Cygwin and links it to MACRO.',
    descriptionJa: 'Cygwin に接続した Tera Term を起動して MACRO とリンク',
    returnsJa: '`result` … 0=Tera Term とリンクなし, 1=リンク済みだがホストまたはCygwinに未接続, 2=リンク・接続済み。',
    returns: '`result` … 0=not linked to Tera Term, 1=linked but not connected to the host or Cygwin, 2=linked and connected.',
  },
  {
    name: 'disconnect',
    signature: 'disconnect [<confirm>]',
    description: 'Disconnects Tera Term from the host.',
    descriptionJa: 'Tera Term とホストの接続を切断',
  },
  {
    name: 'closett',
    signature: 'closett',
    description: 'Closes Tera Term and enters the unlinked state.',
    descriptionJa: 'Tera Term を終了し MACRO は非リンク状態に移行',
  },
  {
    name: 'unlink',
    signature: 'unlink',
    description: 'MACRO enters the unlinked state and can no longer control the Tera Term window.',
    descriptionJa: 'MACRO を非リンク状態にして Tera Term ウィンドウ制御を終了',
  },
  {
    name: 'testlink',
    signature: 'testlink',
    description: 'Tests the link and connection status. Sets "result" to 0 (no link), 1 (linked, not connected), or 2 (linked and connected).',
    descriptionJa: 'リンク・接続状態を result に格納（0=非リンク、1=リンク未接続、2=リンク接続）',
    returnsJa: '`result` … 0=リンクなし, 1=リンク済み未接続, 2=リンク・接続済み。',
    returns: '`result` … 0=not linked, 1=linked but not connected, 2=linked and connected.',
  },
  // ── 一時停止 ─────────────────────────────────────────────────────────────────
  {
    name: 'pause',
    signature: 'pause <time>',
    description: 'Pauses for <time> seconds.',
    descriptionJa: 'TTL 実行を <time> 秒間休止',
    snippet: 'pause ${1:1}',
  },
  {
    name: 'mpause',
    signature: 'mpause <time>',
    description: 'Pauses for <time> milliseconds.',
    descriptionJa: 'TTL 実行を <time> ミリ秒間休止',
    snippet: 'mpause ${1:500}',
  },
  // ── ダイアログ ───────────────────────────────────────────────────────────────
  {
    name: 'messagebox',
    signature: 'messagebox <message> <title> [<special>]',
    description: 'Displays a message box.',
    descriptionJa: 'メッセージボックスを表示',
    snippet: "messagebox '${1:message}' '${2:title}'",
  },
  {
    name: 'inputbox',
    signature: 'inputbox <message> <title> [<default> [<special>]]',
    description: 'Displays an input dialog box. The user input is stored in "inputstr".',
    descriptionJa: '入力ダイアログを表示して inputstr に格納',
    returnsJa: '`inputstr` … 入力された文字列が代入される。',
    returns: '`inputstr` … the string entered by the user.',
    snippet: "inputbox '${1:message}' '${2:title}'",
  },
  {
    name: 'passwordbox',
    signature: 'passwordbox <message> <title> [<special>]',
    description: 'Displays a password input dialog. The input is masked and stored in "inputstr".',
    descriptionJa: 'パスワード入力ダイアログを表示して inputstr に格納',
    returnsJa: '`inputstr` … 入力された文字列が代入される。',
    returns: '`inputstr` … the string entered by the user.',
    snippet: "passwordbox '${1:message}' '${2:title}'",
  },
  {
    name: 'yesnobox',
    signature: 'yesnobox <message> <title> [<special>]',
    description: 'Displays a Yes/No dialog. Sets "result" to 1 for Yes, 0 for No.',
    descriptionJa: 'Yes/No ダイアログを表示して result に格納（Yes=1, No=0）',
    returnsJa: '`result` … 「はい」で 1、「いいえ」で 0。',
    returns: '`result` … set to 1 for "Yes", 0 for "No".',
    snippet: "yesnobox '${1:message}' '${2:title}'",
  },
  {
    name: 'listbox',
    signature: 'listbox <message> <title> <string array> [<selected>] [<keyword parameter>...]',
    description: 'Displays a list box dialog. The selected index is stored in "result".',
    descriptionJa: 'リストボックスダイアログを表示して result に選択インデックスを格納',
    returnsJa: '`result` … 選択した項目の番号 0〜N-1、キャンセル時は -1。',
    returns: '`result` … the selected item index 0 to N-1, or -1 if cancelled.',
    snippet: "listbox '${1:message}' '${2:title}' ${3:array}",
  },
  {
    name: 'statusbox',
    signature: 'statusbox <message> <title> [<special>]',
    description: 'Displays or updates the status dialog box.',
    descriptionJa: 'ステータスダイアログを表示または更新',
    snippet: "statusbox '${1:message}' '${2:title}'",
  },
  {
    name: 'closesbox',
    signature: 'closesbox',
    description: 'Closes the status dialog box opened by the "statusbox" command.',
    descriptionJa: 'statusbox で開いたステータスダイアログを閉じる',
  },
  {
    name: 'bringupbox',
    signature: 'bringupbox',
    description: 'Brings the status box to the top of the Z order.',
    descriptionJa: 'ステータスボックスを最前面に表示',
  },
  {
    name: 'dirnamebox',
    signature: 'dirnamebox <title> [<initialdir>]',
    description: 'Displays a folder browser dialog. The selected folder is stored in "inputstr".',
    descriptionJa: 'フォルダ選択ダイアログを表示して inputstr に格納',
    returnsJa: '`result` … OK を押すと 1（`inputstr` に選択ディレクトリ名）、キャンセル/閉じると 0。',
    returns: '`result` … set to 1 when OK is pressed (`inputstr` holds the directory name), 0 when cancelled or closed.',
    snippet: "dirnamebox '${1:title}'",
  },
  {
    name: 'filenamebox',
    signature: 'filenamebox <title> [<dialogtype> [<initialdir>]]',
    description: 'Displays a file open/save dialog. The selected filename is stored in "inputstr".',
    descriptionJa: 'ファイル選択ダイアログを表示して inputstr に格納',
    returnsJa: '`result` … OK を押すと 0 以外（`inputstr` に入力ファイル名）、キャンセル/閉じると 0。*(4.65 以降)*',
    returns: '`result` … nonzero when OK is pressed (`inputstr` holds the file name), 0 when cancelled or closed. *(4.65 or later)*',
    snippet: "filenamebox '${1:title}'",
  },
  {
    name: 'setdlgpos',
    signature: 'setdlgpos [<x> <y> [<position> [<offset x> <offset y>]]]',
    description: 'Changes the display position of dialog boxes shown by MACRO commands.',
    descriptionJa: 'マクロコマンドのダイアログ表示位置を変更',
  },
  // ── 文字列操作 ───────────────────────────────────────────────────────────────
  {
    name: 'sprintf',
    signature: 'sprintf <format> [<arg1> ...]',
    description: 'Formats the arguments according to the C printf format and stores the result in "inputstr".',
    descriptionJa: '引数を C printf 形式でフォーマットして inputstr に代入',
    returnsJa: '整形結果を `inputstr` に格納。`result` … 0=成功, 1=書式指定なし, 2=書式不正, 3=引数不正。',
    returns: 'Stores the formatted string in `inputstr`. `result` … 0=success, 1=no format, 2=invalid format, 3=invalid argument.',
    snippet: "sprintf '${1:%s}' ${2:arg}",
  },
  {
    name: 'sprintf2',
    signature: 'sprintf2 <strvar> <format> [<arg1> ...]',
    description: 'Formats the arguments according to the C printf format and stores the result in <strvar>.',
    descriptionJa: '引数を C printf 形式でフォーマットして <strvar> に代入',
    returnsJa: '整形結果を `<strvar>` に格納。`result` … 0=成功, 1=書式指定なし, 2=書式不正, 3=引数不正, 4=格納先変数が不正。',
    returns: 'Stores the formatted string in `<strvar>`. `result` … 0=success, 1=no format, 2=invalid format, 3=invalid argument, 4=invalid target variable.',
    snippet: "sprintf2 ${1:strvar} '${2:%s}' ${3:arg}",
  },
  {
    name: 'strconcat',
    signature: 'strconcat <strvar> <string>',
    description: 'Appends a copy of <string> to the end of the string variable <strvar>.',
    descriptionJa: '文字列変数 <strvar> の文字列値の最後に文字列 <string> を継ぎ足す',
    returnsJa: '`<string>` を末尾に連結した結果を `<strvar>` に格納。',
    returns: 'Appends `<string>` to `<strvar>` in place.',
    snippet: 'strconcat ${1:strvar} ${2:string}',
  },
  {
    name: 'strcopy',
    signature: 'strcopy <string> <pos> <len> <strvar>',
    description: 'Copies a substring of <string> (starting at <pos>, length <len>) to <strvar>.',
    descriptionJa: '文字列 <string> の <pos> 文字目から <len> 文字分を文字列変数 <strvar> にコピーする',
    returnsJa: '抽出した部分文字列を `<strvar>` に格納。',
    returns: 'Stores the extracted substring in `<strvar>`.',
    snippet: 'strcopy ${1:string} ${2:1} ${3:len} ${4:strvar}',
  },
  {
    name: 'strlen',
    signature: 'strlen <string>',
    description: 'Returns the byte length of <string> in the system variable "result".',
    descriptionJa: '文字列 <string> の長さをシステム変数 result に格納する',
    returnsJa: '`result` … 文字列の長さ。',
    returns: '`result` … the length of the string.',
    snippet: 'strlen ${1:string}',
  },
  {
    name: 'strscan',
    signature: 'strscan <string> <substring>',
    description: 'Searches for <substring> in <string>. Returns its 1-origin position in "result", or 0 if not found.',
    descriptionJa: '文字列 <string> の中に部分文字列 <substring> が含まれているか調べる。位置(1オリジン)が result に格納される',
    returnsJa: '`result` … `<substring>` が見つかった位置（1 始まり、複数あれば最初）、見つからなければ 0。',
    returns: '`result` … the 1-based position of `<substring>` (the first if there are several), or 0 if not found.',
    snippet: 'strscan ${1:string} ${2:substring}',
  },
  {
    name: 'strmatch',
    signature: 'strmatch <target string> <regex>',
    description: 'Searches <target string> using a regular expression. Matched substrings are stored in groupmatchstr1-9.',
    descriptionJa: '<target string> を正規表現で検索する。マッチした部分が groupmatchstr1〜9 に格納される',
    returnsJa: '`result` … マッチしないと 0、マッチするとその位置（1 始まり）。`matchstr` に最初のマッチ、`groupmatchstr1`〜`groupmatchstr9` にグループマッチ結果。',
    returns: '`result` … 0 if no match, otherwise the 1-based position of the match. `matchstr` holds the first match; `groupmatchstr1`–`groupmatchstr9` hold the captured groups.',
    snippet: "strmatch ${1:string} '${2:regex}'",
  },
  {
    name: 'strreplace',
    signature: 'strreplace <strvar> <index> <regex> <newstr>',
    description: 'Replaces a regex match in <strvar> starting at <index> with <newstr>.',
    descriptionJa: '文字列変数 <strvar> の <index> 位置から正規表現 <regex> を検索し、<newstr> に置き換える',
    returnsJa: '置換結果を `<strvar>` に格納。`result` … 置換成功で 1、不一致で 0、書式エラーで -1。`matchstr` にマッチ文字列。`groupmatchstr1`〜`groupmatchstr9` はクリアされる。',
    returns: 'Stores the replaced string in `<strvar>`. `result` … 1 on a successful replace, 0 if no match, -1 on a regex error. `matchstr` holds the matched string; `groupmatchstr1`–`groupmatchstr9` are cleared.',
    snippet: "strreplace ${1:strvar} 1 '${2:regex}' '${3:newstr}'",
  },
  {
    name: 'strremove',
    signature: 'strremove <strvar> <index> <len>',
    description: 'Deletes <len> characters from <strvar> beginning at <index> (1-origin).',
    descriptionJa: '文字列変数 <strvar> の <index> 位置（1オリジン）から <len> 文字分を削除する',
    returnsJa: '指定範囲を削除した文字列を `<strvar>` に格納。',
    returns: 'Stores the string with the specified range removed in `<strvar>`.',
    snippet: 'strremove ${1:strvar} ${2:1} ${3:len}',
  },
  {
    name: 'strinsert',
    signature: 'strinsert <strvar> <index> <string>',
    description: 'Inserts <string> at position <index> (1-origin) in <strvar>.',
    descriptionJa: '文字列変数 <strvar> の <index> 位置（1オリジン）に文字列 <string> を挿入する',
    returnsJa: '文字列を挿入した結果を `<strvar>` に格納。',
    returns: 'Stores the string with the text inserted in `<strvar>`.',
    snippet: 'strinsert ${1:strvar} ${2:1} ${3:string}',
  },
  {
    name: 'strcompare',
    signature: 'strcompare <string1> <string2>',
    description: 'Compares two strings. Sets "result" to 0 (equal), 1 (string1 > string2), or -1 (string1 < string2).',
    descriptionJa: '2つの文字列を比較し、結果をシステム変数 result に代入する（0: 等しい、1: 大、-1: 小）',
    returnsJa: '`result` … `<string1>` < `<string2>` で -1、等しいと 0、`<string1>` > `<string2>` で 1。',
    returns: '`result` … -1 if `<string1>` < `<string2>`, 0 if equal, 1 if `<string1>` > `<string2>`.',
    snippet: 'strcompare ${1:string1} ${2:string2}',
  },
  {
    name: 'strsplit',
    signature: 'strsplit <strval> <separator> [<count>]',
    description: 'Splits <strval> by <separator> and stores parts in groupmatchstr1-9.',
    descriptionJa: '文字列 <strval> を区切り記号 <separator> で分割し、groupmatchstr1〜9 に返す',
    returnsJa: '区切り文字で分割した部分文字列を `groupmatchstr1`〜`groupmatchstr9` に格納。`result` … 実際に分割された個数（`<count>` 省略時に 9 を超えると 10）。',
    returns: 'Stores the split substrings in `groupmatchstr1` to `groupmatchstr9`. `result` … the number of splits (10 if more than 9 when `<count>` is omitted).',
    snippet: "strsplit ${1:strval} '${2:,}'",
  },
  {
    name: 'strjoin',
    signature: 'strjoin <strvar> <separator> [<count>]',
    description: 'Concatenates groupmatchstr1-9 with <separator> and stores the result in <strvar>.',
    descriptionJa: 'groupmatchstr1〜9 を区切り記号 <separator> で連結し、文字列変数 <strvar> に格納する',
    returnsJa: '`groupmatchstr1`〜`groupmatchstr9` を `<separator>` で連結し `<strvar>` に格納。',
    returns: 'Concatenates `groupmatchstr1` to `groupmatchstr9` with `<separator>` into `<strvar>`.',
    snippet: "strjoin ${1:strvar} '${2:,}'",
  },
  {
    name: 'strtrim',
    signature: 'strtrim <strvar> <trimchars>',
    description: 'Removes all leading and trailing occurrences of <trimchars> from <strvar>.',
    descriptionJa: '文字列変数 <strvar> の先頭と末尾から <trimchars> で指定された文字をすべて削除する',
    returnsJa: 'トリム後の文字列を `<strvar>` に格納。',
    returns: 'Stores the trimmed string in `<strvar>`.',
    snippet: "strtrim ${1:strvar} ' '",
  },
  {
    name: 'strspecial',
    signature: 'strspecial <strvar> [<strval>]',
    description: 'Converts special character sequences (like \\n, \\t) in the string to actual characters.',
    descriptionJa: '渡された文字列に含まれる特殊文字を変換する',
    returnsJa: '特殊文字へ変換した結果を `<strvar>` に格納。',
    returns: 'Stores the converted string in `<strvar>`.',
    snippet: 'strspecial ${1:strvar}',
  },
  {
    name: 'tolower',
    signature: 'tolower <strvar> <string>',
    description: 'Converts all alphabetic characters in <string> to lower-case and returns the result in <strvar>.',
    descriptionJa: '<string> に含まれるアルファベットを全て小文字にし、<strvar> に代入する',
    returnsJa: '小文字へ変換した結果を `<strvar>` に格納。',
    returns: 'Stores the lower-cased string in `<strvar>`.',
    snippet: 'tolower ${1:strvar} ${2:string}',
  },
  {
    name: 'toupper',
    signature: 'toupper <strvar> <string>',
    description: 'Converts all alphabetic characters in <string> to upper-case and returns the result in <strvar>.',
    descriptionJa: '<string> に含まれるアルファベットを全て大文字にし、<strvar> に代入する',
    returnsJa: '大文字へ変換した結果を `<strvar>` に格納。',
    returns: 'Stores the upper-cased string in `<strvar>`.',
    snippet: 'toupper ${1:strvar} ${2:string}',
  },
  {
    name: 'int2str',
    signature: 'int2str <strvar> <integer value>',
    description: 'Converts <integer value> to its decimal string expression and stores it in <strvar>.',
    descriptionJa: '整数値 <integer value> を10進表現の文字列に変換して文字列型変数 <strvar> に代入する',
    returnsJa: '文字列へ変換した結果を `<strvar>` に格納。',
    returns: 'Stores the string representation in `<strvar>`.',
    snippet: 'int2str ${1:strvar} ${2:value}',
  },
  {
    name: 'str2int',
    signature: 'str2int <intvar> <string>',
    description: 'Converts the decimal or hexadecimal <string> to its numeric value and stores it in <intvar>.',
    descriptionJa: '文字列 <string> を整数値に変換し、整数変数 <intvar> に代入する',
    returnsJa: '変換結果を `<intvar>` に格納。`result` … 変換成功で 1、失敗で 0。',
    returns: 'Stores the converted value in `<intvar>`. `result` … set to 1 on success, 0 on failure.',
    snippet: 'str2int ${1:intvar} ${2:string}',
  },
  {
    name: 'str2code',
    signature: 'str2code <intvar> <string>',
    description: 'Copies the ASCII code of the first character of <string> to <intvar>.',
    descriptionJa: '文字列 <string> が1文字の場合、その ASCII コードを整数変数 <intvar> に格納する',
    returnsJa: 'ASCII コード（最大4文字分）を `<intvar>` に格納。',
    returns: 'Stores the ASCII code(s) (up to 4 characters) in `<intvar>`.',
    snippet: 'str2code ${1:intvar} ${2:string}',
  },
  {
    name: 'code2str',
    signature: 'code2str <strvar> <ASCII code>',
    description: 'Converts an ASCII code value to its character and stores it in <strvar>.',
    descriptionJa: '整数値 <ASCII code> に対応する文字を文字列変数 <strvar> に格納する',
    returnsJa: 'ASCII コードに対応する文字列を `<strvar>` に格納。',
    returns: 'Stores the characters for the given ASCII code(s) in `<strvar>`.',
    snippet: 'code2str ${1:strvar} ${2:code}',
  },
  {
    name: 'regexoption',
    signature: 'regexoption <option1> [<option2> ...]',
    description: 'Specifies the syntax, encoding, and options of the regular expression.',
    descriptionJa: 'strmatch, strreplace, waitregex で使用する正規表現の文法と文字エンコーディングを指定する',
  },
  // ── 数値演算 ─────────────────────────────────────────────────────────────────
  {
    name: 'random',
    signature: 'random <intvar> <max number>',
    description: 'Generates a random integer within the range 0..<max number> and assigns it to <intvar>.',
    descriptionJa: '0から<max number>までの整数の一様乱数を生成し、整数変数 <integer variable> へ代入する',
    returnsJa: '生成した乱数を `<intvar>` に格納。',
    returns: 'Stores the generated random number in `<intvar>`.',
    snippet: 'random ${1:intvar} ${2:100}',
  },
  {
    name: 'rotateleft',
    signature: 'rotateleft <intvar> <intval> <count>',
    description: 'Rotates <intval> left by <count> bits and stores the result in <intvar>.',
    descriptionJa: '整数値 <intval> を左に <count> 桁ローテートした値を整数型変数 <intvar> にコピーする',
    returnsJa: '左へローテートした結果を `<intvar>` に格納。',
    returns: 'Stores the left-rotated value in `<intvar>`.',
    snippet: 'rotateleft ${1:intvar} ${2:intval} ${3:count}',
  },
  {
    name: 'rotateright',
    signature: 'rotateright <intvar> <intval> <count>',
    description: 'Rotates <intval> right by <count> bits and stores the result in <intvar>.',
    descriptionJa: '整数値 <intval> を右に <count> 桁ローテートした値を整数型変数 <intvar> にコピーする',
    returnsJa: '右へローテートした結果を `<intvar>` に格納。',
    returns: 'Stores the right-rotated value in `<intvar>`.',
    snippet: 'rotateright ${1:intvar} ${2:intval} ${3:count}',
  },
  {
    name: 'checksum8',
    signature: 'checksum8 <intvar> <string>',
    description: 'Calculates the 8-bit checksum of a string.',
    descriptionJa: '引数の文字列から加算サム(8bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。',
    returns: 'Stores the computed checksum in `<intvar>`.',
    snippet: 'checksum8 ${1:intvar} ${2:string}',
  },
  {
    name: 'checksum8file',
    signature: 'checksum8file <intvar> <filename>',
    description: 'Calculates the 8-bit checksum of a file.',
    descriptionJa: 'ファイルから加算サム(8bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。ファイルを開けない場合は `result` に -1。',
    returns: 'Stores the computed checksum in `<intvar>`. `result` is set to -1 if the file cannot be opened.',
    snippet: "checksum8file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'checksum16',
    signature: 'checksum16 <intvar> <string>',
    description: 'Calculates the 16-bit checksum of a string.',
    descriptionJa: '引数の文字列から加算サム(16bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。',
    returns: 'Stores the computed checksum in `<intvar>`.',
    snippet: 'checksum16 ${1:intvar} ${2:string}',
  },
  {
    name: 'checksum16file',
    signature: 'checksum16file <intvar> <filename>',
    description: 'Calculates the 16-bit checksum of a file.',
    descriptionJa: 'ファイルから加算サム(16bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。ファイルを開けない場合は `result` に -1。',
    returns: 'Stores the computed checksum in `<intvar>`. `result` is set to -1 if the file cannot be opened.',
    snippet: "checksum16file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'checksum32',
    signature: 'checksum32 <intvar> <string>',
    description: 'Calculates the 32-bit checksum of a string.',
    descriptionJa: '引数の文字列から加算サム(32bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。',
    returns: 'Stores the computed checksum in `<intvar>`.',
    snippet: 'checksum32 ${1:intvar} ${2:string}',
  },
  {
    name: 'checksum32file',
    signature: 'checksum32file <intvar> <filename>',
    description: 'Calculates the 32-bit checksum of a file.',
    descriptionJa: 'ファイルから加算サム(32bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。ファイルを開けない場合は `result` に -1。',
    returns: 'Stores the computed checksum in `<intvar>`. `result` is set to -1 if the file cannot be opened.',
    snippet: "checksum32file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'crc16',
    signature: 'crc16 <intvar> <string>',
    description: 'Calculates the 16-bit CRC of a string.',
    descriptionJa: '引数の文字列からCRC(16bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。',
    returns: 'Stores the computed CRC in `<intvar>`.',
    snippet: 'crc16 ${1:intvar} ${2:string}',
  },
  {
    name: 'crc16file',
    signature: 'crc16file <intvar> <filename>',
    description: 'Calculates the 16-bit CRC of a file.',
    descriptionJa: 'ファイルからCRC(16bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。ファイルを開けない場合は `result` に -1。',
    returns: 'Stores the computed CRC in `<intvar>`. `result` is set to -1 if the file cannot be opened.',
    snippet: "crc16file ${1:intvar} '${2:filename}'",
  },
  {
    name: 'crc32',
    signature: 'crc32 <intvar> <string>',
    description: 'Calculates the 32-bit CRC of a string.',
    descriptionJa: '引数の文字列からCRC(32bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。',
    returns: 'Stores the computed CRC in `<intvar>`.',
    snippet: 'crc32 ${1:intvar} ${2:string}',
  },
  {
    name: 'crc32file',
    signature: 'crc32file <intvar> <filename>',
    description: 'Calculates the 32-bit CRC of a file.',
    descriptionJa: 'ファイルからCRC(32bit)を計算する',
    returnsJa: '計算結果を `<intvar>` に格納。ファイルを開けない場合は `result` に -1。',
    returns: 'Stores the computed CRC in `<intvar>`. `result` is set to -1 if the file cannot be opened.',
    snippet: "crc32file ${1:intvar} '${2:filename}'",
  },
  // ── ファイル操作 ─────────────────────────────────────────────────────────────
  {
    name: 'fileopen',
    signature: 'fileopen <file handle> <filename> <append flag> [<readonly flag>]',
    description: 'Opens a file in binary mode.',
    descriptionJa: 'ファイルをバイナリモードでオープンする',
    returnsJa: 'ファイルハンドルを `<file handle>` に格納。オープンに失敗すると `<file handle>` に -1。',
    returns: 'Stores the file handle in `<file handle>`; if the file cannot be opened, `<file handle>` is set to -1.',
    snippet: "fileopen ${1:fp} '${2:filename}' ${3:0}",
  },
  {
    name: 'fileclose',
    signature: 'fileclose <file handle>',
    description: 'Closes the file specified by <file handle>.',
    descriptionJa: 'ファイルハンドル <file handle> で指定されるファイルをクローズする',
    snippet: 'fileclose ${1:fp}',
  },
  {
    name: 'filecreate',
    signature: 'filecreate <file handle> <filename>',
    description: 'Creates and opens a new file.',
    descriptionJa: 'ファイル <filename> を新しく作成しオープンする',
    returnsJa: 'ファイルハンドルを `<file handle>` に格納（失敗時は -1）。`result` … 成功すると 0、失敗すると 0 以外。',
    returns: 'Stores the file handle in `<file handle>` (-1 on failure). `result` … set to 0 on success, non-zero on failure.',
    snippet: "filecreate ${1:fp} '${2:filename}'",
  },
  {
    name: 'fileread',
    signature: 'fileread <file handle> <read byte> <strvar>',
    description: 'Reads <read byte> bytes from the file into <strvar>.',
    descriptionJa: '<file handle> で指定されたファイルから指定したバイト数のデータを読み出す',
    returnsJa: '読み込んだデータを `<strvar>` に格納。`result` … 読み込み中にファイル終端へ達すると 1、それ以外は 0。',
    returns: 'Stores the read data in `<strvar>`. `result` … set to 1 if the end of file is reached before reading completes, 0 otherwise.',
    snippet: 'fileread ${1:fp} ${2:512} ${3:strvar}',
  },
  {
    name: 'filereadln',
    signature: 'filereadln <file handle> <strvar>',
    description: 'Reads one line from the file into <strvar>.',
    descriptionJa: 'ファイルから一行読む。読み込まれた行は文字列変数 <strvar> に格納される',
    returnsJa: '読み込んだ行を `<strvar>` に格納。ファイル終端に達すると `result` に 1、それ以外は 0（改行のみの行では `<strvar>` は空、`result` は 0）。',
    returns: 'Stores the line in `<strvar>`. `result` is set to 1 at end of file, 0 otherwise (a newline-only line yields an empty `<strvar>` and `result` 0).',
    snippet: 'filereadln ${1:fp} ${2:strvar}',
  },
  {
    name: 'filewrite',
    signature: 'filewrite <file handle> <data>',
    description: 'Writes <data> to the file.',
    descriptionJa: 'ファイルハンドル <file handle> で指定されるファイルへ <data> を書き込む',
    snippet: 'filewrite ${1:fp} ${2:data}',
  },
  {
    name: 'filewriteln',
    signature: 'filewriteln <file handle> <data>',
    description: 'Writes <data> and CR+LF to the file.',
    descriptionJa: 'ファイルへ <data> と改行文字 (CR+LF) を書き込む',
    snippet: 'filewriteln ${1:fp} ${2:data}',
  },
  {
    name: 'fileseek',
    signature: 'fileseek <file handle> <offset> <origin>',
    description: 'Moves the file pointer. <origin>: 0=beginning, 1=current, 2=end.',
    descriptionJa: 'ファイルポインタを移動する。<origin>: 0=先頭, 1=現在位置, 2=末尾',
    snippet: 'fileseek ${1:fp} ${2:0} ${3:0}',
  },
  {
    name: 'fileseekback',
    signature: 'fileseekback <file handle>',
    description: 'Moves the file pointer to the position marked by "filemarkptr".',
    descriptionJa: '"filemarkptr" コマンドで保存したファイルポインタ位置に戻る',
    snippet: 'fileseekback ${1:fp}',
  },
  {
    name: 'filemarkptr',
    signature: 'filemarkptr <file handle>',
    description: 'Marks the current file pointer position.',
    descriptionJa: 'オープンされているファイルの現在のファイルポインタを保存する',
    snippet: 'filemarkptr ${1:fp}',
  },
  {
    name: 'filestat',
    signature: 'filestat <filename> <size> [<mtime>] [<drive>]',
    description: 'Obtains information about a file or directory.',
    descriptionJa: 'ファイルもしくはフォルダの統計情報を取得する',
    returnsJa: 'ファイル情報を各変数に格納。取得に失敗すると `result` に -1。',
    returns: 'Stores file information in the given variables. `result` is set to -1 on failure.',
    snippet: "filestat '${1:filename}' ${2:size}",
  },
  {
    name: 'filestrseek',
    signature: 'filestrseek <file handle> <string>',
    description: 'Searches for <string> in the file from the current position forward.',
    descriptionJa: 'ファイルから文字列 <string> を前方検索する',
    returnsJa: '`result` … 文字列が見つかると 1（ファイルポインタは直後へ移動）、見つからないと 0（移動なし）。',
    returns: '`result` … set to 1 if the string is found (the file pointer moves just after it), 0 if not (pointer unchanged).',
    snippet: "filestrseek ${1:fp} '${2:string}'",
  },
  {
    name: 'filestrseek2',
    signature: 'filestrseek2 <file handle> <string>',
    description: 'Searches for <string> in the file from the current position backward.',
    descriptionJa: 'ファイルから文字列 <string> を後方検索する',
    returnsJa: '`result` … 文字列が見つかると 1（ファイルポインタは直前へ移動）、見つからないと 0（移動なし）。実行前にファイルポインタがすでに 0 の場合も 0。',
    returns: '`result` … set to 1 if the string is found (the file pointer moves just before it), 0 if not (pointer unchanged). Also 0 if the file pointer is already at position 0 before execution.',
    snippet: "filestrseek2 ${1:fp} '${2:string}'",
  },
  {
    name: 'filetruncate',
    signature: 'filetruncate <filename> <size>',
    description: 'Changes the size of a file to <size> bytes.',
    descriptionJa: 'ファイル <filename> をサイズ <size> バイトの大きさに変更する',
    returnsJa: '`result` … サイズ変更に成功すると 0、失敗すると -1。',
    returns: '`result` … set to 0 if the size change succeeds, -1 on error.',
  },
  {
    name: 'filecopy',
    signature: 'filecopy <file1> <file2>',
    description: 'Copies <file1> to <file2>. Sets "result" to 0 on success.',
    descriptionJa: 'ファイル <file1> をコピーし、ファイル <file2> を作成する',
    returnsJa: '`result` … 成功で 0、失敗で 0 以外（-1〜-4 はファイル名不正・同名・コピー失敗などの状態コード）。',
    returns: '`result` … 0 on success, non-zero on failure (-1 to -4 indicate status such as an invalid file name, identical names, or copy failure).',
    snippet: "filecopy '${1:file1}' '${2:file2}'",
  },
  {
    name: 'filerename',
    signature: 'filerename <file1> <file2>',
    description: 'Renames <file1> to <file2>. Sets "result" to 0 on success.',
    descriptionJa: 'ファイル <file1> を <file2> という名前に変更する',
    returnsJa: '`result` … 成功すると 0、失敗すると 0 以外。',
    returns: '`result` … set to 0 on success, non-zero on failure.',
    snippet: "filerename '${1:file1}' '${2:file2}'",
  },
  {
    name: 'filedelete',
    signature: 'filedelete <filename>',
    description: 'Deletes the specified file. Sets "result" to 0 on success.',
    descriptionJa: 'ファイル <filename> を削除する',
    returnsJa: '`result` … 成功すると 0、失敗すると 0 以外。',
    returns: '`result` … set to 0 on success, non-zero on failure.',
    snippet: "filedelete '${1:filename}'",
  },
  {
    name: 'filesearch',
    signature: 'filesearch <filename>',
    description: 'Searches for a file or folder. Sets "result" to 1 if found, 0 if not.',
    descriptionJa: 'ファイルまたはフォルダが存在するか調べる。存在する場合は result に 1 が返る',
    returnsJa: '`result` … ファイルが存在すれば 1、存在しなければ 0。',
    returns: '`result` … set to 1 if the file exists, 0 if not.',
    snippet: "filesearch '${1:filename}'",
  },
  {
    name: 'fileconcat',
    signature: 'fileconcat <file1> <file2>',
    description: 'Appends a copy of <file2> to the end of <file1>.',
    descriptionJa: 'ファイル <file2> の内容をファイル <file1> の最後に追加する',
    returnsJa: '`result` … 成功すると 0、失敗すると 0 以外。',
    returns: '`result` … set to 0 on success, non-zero on failure.',
    snippet: "fileconcat '${1:file1}' '${2:file2}'",
  },
  {
    name: 'filelock',
    signature: 'filelock <file handle> [<timeout>]',
    description: 'Locks the file for exclusive access.',
    descriptionJa: 'ファイル全体をロックし、他のプロセスからのアクセスを禁止する',
    returnsJa: '`result` … ロックに成功すると 0、失敗すると 1。',
    returns: '`result` … set to 0 when the lock succeeds, 1 when it fails.',
    snippet: 'filelock ${1:fp}',
  },
  {
    name: 'fileunlock',
    signature: 'fileunlock <file handle>',
    description: 'Unlocks the file.',
    descriptionJa: 'ファイル全体のロックを解除する',
    returnsJa: '`result` … 解除に成功すると 0、失敗すると 1。',
    returns: '`result` … set to 0 when the unlock succeeds, 1 when it fails.',
    snippet: 'fileunlock ${1:fp}',
  },
  // ── フォルダ操作 ─────────────────────────────────────────────────────────────
  {
    name: 'foldercreate',
    signature: 'foldercreate <foldername>',
    description: 'Creates a new folder. Sets "result" to 0 on success.',
    descriptionJa: 'フォルダ <foldername> を新しく作成する',
    returnsJa: '`result` … 成功すると 0、失敗すると 0 以外。',
    returns: '`result` … set to 0 on success, non-zero on failure.',
    snippet: "foldercreate '${1:foldername}'",
  },
  {
    name: 'folderdelete',
    signature: 'folderdelete <foldername>',
    description: 'Deletes a folder. Sets "result" to 0 on success.',
    descriptionJa: 'フォルダ <foldername> を削除する',
    returnsJa: '`result` … 成功すると 0、失敗すると 0 以外。',
    returns: '`result` … set to 0 on success, non-zero on failure.',
    snippet: "folderdelete '${1:foldername}'",
  },
  {
    name: 'foldersearch',
    signature: 'foldersearch <foldername>',
    description: 'Searches for a folder. Sets "result" to 1 if found, 0 if not.',
    descriptionJa: 'フォルダが存在するか調べる。存在する場合は result に 1 が返る',
    returnsJa: '`result` … フォルダが存在すれば 1、存在しなければ 0。',
    returns: '`result` … set to 1 if the folder exists, 0 if not.',
    snippet: "foldersearch '${1:foldername}'",
  },
  // ── ファイル検索 ─────────────────────────────────────────────────────────────
  {
    name: 'findfirst',
    signature: 'findfirst <dir handle> <file name> <strvar>',
    description: 'Searches for the first file matching the specified pattern.',
    descriptionJa: 'findfirst コマンドはファイル名パターンに合致する最初のファイルを探す',
    returnsJa: 'ファイルが見つかると `<dir handle>` にハンドル、`<strvar>` にファイル名、`result` に 1 を格納。見つからないと それぞれ -1・空文字列・0。',
    returns: 'On a match, sets `<dir handle>` to the handle, `<strvar>` to the file name, and `result` to 1. Otherwise they are set to -1, "" and 0.',
    snippet: "findfirst ${1:handle} '${2:*.ttl}' ${3:strvar}",
  },
  {
    name: 'findnext',
    signature: 'findnext <dir handle> <strvar>',
    description: 'Searches for the next file matching the pattern set by "findfirst".',
    descriptionJa: '"findfirst" で設定したパターンに合致する次のファイルを探す',
    returnsJa: '次のファイルが見つかると `<strvar>` にファイル名、`result` に 1 を格納。見つからないと 空文字列・0。',
    returns: 'On the next match, sets `<strvar>` to the file name and `result` to 1. Otherwise "" and 0.',
    snippet: 'findnext ${1:handle} ${2:strvar}',
  },
  {
    name: 'findclose',
    signature: 'findclose <dir handle>',
    description: 'Closes the file search opened by "findfirst".',
    descriptionJa: '"findfirst" で開いたファイル検索を閉じる',
    snippet: 'findclose ${1:handle}',
  },
  // ── パス操作 ─────────────────────────────────────────────────────────────────
  {
    name: 'basename',
    signature: 'basename <strvar> <path>',
    description: 'Returns the trailing name component of a path.',
    descriptionJa: 'パス名 <path> からファイル名部分を <strvar> に格納する',
    returnsJa: 'パスのファイル名部分を `<strvar>` に格納。',
    returns: 'Stores the file-name part of the path in `<strvar>`.',
    snippet: 'basename ${1:strvar} ${2:path}',
  },
  {
    name: 'dirname',
    signature: 'dirname <strvar> <path>',
    description: 'Returns the directory component of a path.',
    descriptionJa: 'パス名 <path> のディレクトリ名部分を <strvar> に格納する',
    returnsJa: 'パスのディレクトリ名部分を `<strvar>` に格納。',
    returns: 'Stores the directory part of the path in `<strvar>`.',
    snippet: 'dirname ${1:strvar} ${2:path}',
  },
  {
    name: 'makepath',
    signature: 'makepath <strvar> <dir> <name>',
    description: 'Creates a full path name from a directory name and file name.',
    descriptionJa: 'ディレクトリ名 <dir> とファイル名 <name> からフルパス名を作成する',
    returnsJa: '連結したパスを `<strvar>` に格納。',
    returns: 'Stores the assembled path in `<strvar>`.',
    snippet: 'makepath ${1:strvar} ${2:dir} ${3:name}',
  },
  // ── 配列 ─────────────────────────────────────────────────────────────────────
  {
    name: 'intdim',
    signature: 'intdim <array> <size>',
    description: 'Defines an integer array with <size> elements.',
    descriptionJa: '<size> 個の要素を持つ整数配列型の変数 <array> を宣言する',
    snippet: 'intdim ${1:array} ${2:10}',
  },
  {
    name: 'strdim',
    signature: 'strdim <array> <size>',
    description: 'Defines a string array with <size> elements.',
    descriptionJa: '<size> 個の要素を持つ文字列配列型の変数 <array> を宣言する',
    snippet: 'strdim ${1:array} ${2:10}',
  },
  // ── 日時 ─────────────────────────────────────────────────────────────────────
  {
    name: 'getdate',
    signature: 'getdate <strvar> [<format> [<timezone>]]',
    description: 'Returns the current date in <strvar>. Default format is "YYYY-MM-DD".',
    descriptionJa: '現在の日付を文字列変数 <strvar> に格納する。デフォルト形式は "YYYY-MM-DD"',
    returnsJa: '日付を `<strvar>` に格納。`<format>` 指定時は `result` … 0=成功, 1=長さ超過などで失敗, 2=書式不正（`<format>` 省略時は `result` 不変）。',
    returns: 'Stores the date in `<strvar>`. When `<format>` is given, `result` … 0=success, 1=failed (e.g. length over the limit), 2=invalid format (unchanged when `<format>` is omitted).',
    snippet: 'getdate ${1:strvar}',
  },
  {
    name: 'gettime',
    signature: 'gettime <strvar> [<format> [<timezone>]]',
    description: 'Returns the current time in <strvar>. Default format is "HH:MM:SS".',
    descriptionJa: '現在の時刻を文字列変数 <strvar> に格納する。デフォルト形式は "HH:MM:SS"',
    returnsJa: '時刻を `<strvar>` に格納。`<format>` 指定時は `result` … 0=成功, 1=長さ超過などで失敗, 2=書式不正（`<format>` 省略時は `result` 不変）。',
    returns: 'Stores the time in `<strvar>`. When `<format>` is given, `result` … 0=success, 1=failed (e.g. length over the limit), 2=invalid format (unchanged when `<format>` is omitted).',
    snippet: 'gettime ${1:strvar}',
  },
  {
    name: 'setdate',
    signature: 'setdate <date>',
    description: 'Sets the system date. The format of <date> should be "YYYY-MM-DD".',
    descriptionJa: 'システムの日付を変更する。<date> の形式は "YYYY-MM-DD"',
  },
  {
    name: 'settime',
    signature: 'settime <time>',
    description: 'Sets the system time. The format of <time> should be "HH:MM:SS".',
    descriptionJa: 'システムの時刻を変更する。<time> の形式は "HH:MM:SS"',
  },
  {
    name: 'uptime',
    signature: 'uptime <intvar>',
    description: 'Retrieves the number of milliseconds that have elapsed since Windows was started.',
    descriptionJa: 'Windows OS の稼働時間（ミリ秒）を <intvar> に格納する',
    returnsJa: 'OS の稼働時間（ミリ秒）を `<intvar>` に格納。',
    returns: 'Stores the OS uptime in milliseconds in `<intvar>`.',
    snippet: 'uptime ${1:intvar}',
  },
  // ── 環境変数 ─────────────────────────────────────────────────────────────────
  {
    name: 'getenv',
    signature: 'getenv <envname> <strvar>',
    description: 'Retrieves the value of an environment variable and stores it in <strvar>.',
    descriptionJa: '環境変数 <envname> の値を文字列変数 <strvar> に格納する',
    returnsJa: '環境変数の値を `<strvar>` に格納。',
    returns: 'Stores the environment variable value in `<strvar>`.',
    snippet: "getenv '${1:PATH}' ${2:strvar}",
  },
  {
    name: 'setenv',
    signature: 'setenv <envname> <strval>',
    description: 'Sets an environment variable. Effective only within the macro.',
    descriptionJa: '環境変数 <envname> に <strval> をセットする（マクロ内でのみ有効）',
    snippet: "setenv '${1:VAR}' '${2:value}'",
  },
  {
    name: 'expandenv',
    signature: 'expandenv <strvar> [<strval>]',
    description: 'Expands environment variable strings (%VARNAME%) in the string.',
    descriptionJa: '文字列内の環境変数文字列(%variableName%)を展開する',
    returnsJa: '環境変数を展開した文字列を `<strvar>` に格納。',
    returns: 'Stores the expanded string in `<strvar>`.',
    snippet: 'expandenv ${1:strvar}',
  },
  // ── システム情報 ─────────────────────────────────────────────────────────────
  {
    name: 'getver',
    signature: 'getver <strvar> [<version>]',
    description: 'Returns the version of Tera Term in <strvar>.',
    descriptionJa: 'Tera Term のバージョンを <strvar> に格納する',
    returnsJa: 'バージョン文字列を `<strvar>` に格納。`<version>` 指定時は `result` … -2=指定不正, -1=現バージョンが古い, 0=同じ, 1=新しい（省略時は `result` 不変）。',
    returns: 'Stores the version string in `<strvar>`. When `<version>` is given, `result` … -2=invalid, -1=older, 0=same, 1=newer (unchanged when omitted).',
    snippet: 'getver ${1:strvar}',
  },
  {
    name: 'gethostname',
    signature: 'gethostname <strvar>',
    description: 'Retrieves the destination hostname or IP address and stores it in <strvar>.',
    descriptionJa: 'Tera Term が接続しているホスト名（IPアドレス）を文字列変数 <strvar> に格納する',
    returnsJa: 'ホスト名（IPアドレス）を `<strvar>` に格納。',
    returns: 'Stores the host name or IP address in `<strvar>`.',
    snippet: 'gethostname ${1:strvar}',
  },
  {
    name: 'getipv4addr',
    signature: 'getipv4addr <string array> <intvar>',
    description: 'Retrieves the local IPv4 address list.',
    descriptionJa: 'ローカルの IPv4 アドレス一覧を取得する',
    returnsJa: '取得した IP アドレスを `<string array>` に、アドレス個数を `<intvar>` に格納。`result` … 取得成功で 1、配列の要素数が足りない場合 0、取得失敗で -1。',
    returns: 'Stores the retrieved IP addresses in `<string array>` and the count in `<intvar>`. `result` … 1 on success, 0 if the array has too few entries, -1 on failure.',
  },
  {
    name: 'getipv6addr',
    signature: 'getipv6addr <string array> <intvar>',
    description: 'Retrieves the local IPv6 address list.',
    descriptionJa: 'ローカルの IPv6 アドレス一覧を取得する',
    returnsJa: '取得した IP アドレスを `<string array>` に、アドレス個数を `<intvar>` に格納。`result` … 取得成功で 1、配列の要素数が足りない場合 0、取得失敗で -1（Windows 2000 以前では常に失敗）。',
    returns: 'Stores the retrieved IP addresses in `<string array>` and the count in `<intvar>`. `result` … 1 on success, 0 if the array has too few entries, -1 on failure (always fails on Windows 2000 or earlier).',
  },
  {
    name: 'getmodemstatus',
    signature: 'getmodemstatus <intvar>',
    description: 'Retrieves the modem control-register values from the serial port.',
    descriptionJa: 'シリアルポートからモデム制御レジスタの値を読み出す',
    returnsJa: 'モデム制御レジスタの値を `<intvar>` に格納。`result` … 読み出し成功で 0、失敗で 1。',
    returns: 'Stores the modem control-register values in `<intvar>`. `result` … 0 on success, 1 on failure.',
    snippet: 'getmodemstatus ${1:intvar}',
  },
  {
    name: 'getspecialfolder',
    signature: 'getspecialfolder <strvar> <foldertype>',
    description: 'Stores a Windows special folder path in <strvar>.',
    descriptionJa: 'Windows の特殊フォルダを取得して <strvar> に格納する',
    returnsJa: 'フォルダパスを `<strvar>` に格納。`result` … 取得成功で 1、失敗で 0。',
    returns: 'Stores the folder path in `<strvar>`. `result` … 1 on success, 0 on failure.',
    snippet: 'getspecialfolder ${1:strvar} ${2:foldertype}',
  },
  {
    name: 'getttdir',
    signature: 'getttdir <strvar>',
    description: 'Stores the directory of ttpmacro.exe in <strvar>.',
    descriptionJa: 'ttpmacro.exe があるディレクトリを文字列変数 <strvar> に格納する',
    returnsJa: 'ディレクトリパスを `<strvar>` に格納。`result` … 取得成功で 1、失敗で 0。',
    returns: 'Stores the directory path in `<strvar>`. `result` … 1 on success, 0 on failure.',
    snippet: 'getttdir ${1:strvar}',
  },
  {
    name: 'getttpos',
    signature: 'getttpos <showflag> <window x> <window y> <window width> <window height> <client x> <client y> <client width> <client height>',
    description: 'Retrieves the position and size of the Tera Term window.',
    descriptionJa: 'Tera Term ウィンドウの位置とサイズを取得する',
    returnsJa: 'ウィンドウの表示状態・位置・サイズを各変数に格納。`result` … 取得成功で 0、失敗で -1。',
    returns: 'Stores the window display state, position, and size in the respective variables. `result` … 0 on success, -1 on failure.',
    snippet: 'getttpos ${1:showflag} ${2:wx} ${3:wy} ${4:ww} ${5:wh} ${6:cx} ${7:cy} ${8:cw} ${9:ch}',
  },
  {
    name: 'gettitle',
    signature: 'gettitle <strvar>',
    description: 'Retrieves the title text of Tera Term and stores it in <strvar>.',
    descriptionJa: 'Tera Term のウィンドウタイトルを文字列変数 <strvar> に格納する',
    returnsJa: 'ウィンドウタイトルを `<strvar>` に格納。',
    returns: 'Stores the window title in `<strvar>`.',
    snippet: 'gettitle ${1:strvar}',
  },
  {
    name: 'settitle',
    signature: 'settitle <title>',
    description: 'Changes the title text of the Tera Term window.',
    descriptionJa: 'Tera Term のウィンドウタイトルを <title> に変更する',
    snippet: "settitle '${1:title}'",
  },
  // ── ディレクトリ ─────────────────────────────────────────────────────────────
  {
    name: 'getdir',
    signature: 'getdir <strvar>',
    description: 'Returns the current working directory for MACRO (not Tera Term).',
    descriptionJa: 'MACRO のカレントディレクトリを文字列変数 <strvar> に格納する',
    returnsJa: 'MACRO のカレントディレクトリを `<strvar>` に格納。',
    returns: 'Stores the current directory of MACRO in `<strvar>`.',
    snippet: 'getdir ${1:strvar}',
  },
  {
    name: 'setdir',
    signature: 'setdir <dir>',
    description: 'Changes the current working directory for MACRO.',
    descriptionJa: 'MACRO のカレントディレクトリを <dir> に変更する',
    snippet: "setdir '${1:dir}'",
  },
  {
    name: 'changedir',
    signature: 'changedir <path>',
    description: "Changes the file transfer directory for Tera Term to <path>.",
    descriptionJa: 'Tera Term のファイル転送用ディレクトリを <path> に変更する',
    snippet: "changedir '${1:path}'",
  },
  // ── ウィンドウ表示 ───────────────────────────────────────────────────────────
  {
    name: 'show',
    signature: 'show <show flag>',
    description: 'Minimizes MACRO if <show flag> is 0, restores it if positive.',
    descriptionJa: '<show flag> が0の場合 MACRO を最小化する。0より大きい場合は元の大きさに戻して最前面に表示する',
    snippet: 'show ${1:1}',
  },
  {
    name: 'showtt',
    signature: 'showtt <show flag>',
    description: 'Controls the Tera Term VT window visibility: -1=hide, 0=minimize, positive=show.',
    descriptionJa: '<show flag> が-1なら VT ウィンドウを隠す。0なら最小化する。0より大きいなら表示する',
    snippet: 'showtt ${1:1}',
  },
  {
    name: 'clearscreen',
    signature: 'clearscreen <int>',
    description: 'Erases the screen: 0=VT screen, 1=VT screen+scroll buffer, 2=TEK screen.',
    descriptionJa: '<int> が0の場合 VT ウィンドウの画面を消去。1の場合はスクロールバッファーも消去',
    snippet: 'clearscreen ${1:0}',
  },
  {
    name: 'beep',
    signature: 'beep [<sound type>]',
    description: 'Makes a beep sound. Sound types: 0=simple, 1=asterisk, 2=exclamation, 3=critical, 4=question, 5=default.',
    descriptionJa: 'WAVE 形式のサウンドを再生する',
    snippet: 'beep ${1:0}',
  },
  // ── ログ ─────────────────────────────────────────────────────────────────────
  {
    name: 'logopen',
    signature: 'logopen <filename> <binary flag> <append flag> [<plain text flag> [<timestamp flag> [<hide dialog flag> [<include screen buffer flag> [<timestamp type>]]]]]',
    description: 'Opens a log file and starts logging received characters.',
    descriptionJa: 'ログファイルを開いて受信文字のログ採取を開始する',
    returnsJa: '`result` … ログファイルを開けると 0、開けないと 1。*(4.62 以降)*',
    returns: '`result` … set to 0 if the log file is opened, 1 if not. *(4.62 or later)*',
    snippet: "logopen '${1:logfile.log}' 0 0",
  },
  {
    name: 'logclose',
    signature: 'logclose',
    description: 'Closes the log file and stops logging.',
    descriptionJa: 'ログファイルを閉じてログ採取を停止する',
  },
  {
    name: 'logpause',
    signature: 'logpause',
    description: 'Pauses logging. Characters received while paused are discarded.',
    descriptionJa: 'ログ採取を一時中断する。中断中に受信された文字はログファイルに書き込まれない',
  },
  {
    name: 'logstart',
    signature: 'logstart',
    description: 'Restarts logging after "logpause".',
    descriptionJa: '"logpause" で中断したログ採取を再開する',
  },
  {
    name: 'logwrite',
    signature: 'logwrite <string>',
    description: 'Appends a string to the Tera Term log file.',
    descriptionJa: '文字列 <string> を Tera Term のログファイルに追加して書き込む',
    snippet: "logwrite '${1:string}'",
  },
  {
    name: 'loginfo',
    signature: 'loginfo <strvar>',
    description: 'Retrieves the current log filename into <strvar>. Sets "result" to -1 if not logging.',
    descriptionJa: 'ログを取得している場合、strvar にログファイル名が格納される。ログ取得していない場合は result に -1 が格納される',
    returnsJa: 'ログ取得中は `<strvar>` にログファイル名、`result` にフラグ状態を格納。取得していない場合は `result` に -1。',
    returns: 'While logging, stores the log file name in `<strvar>` and the flag status in `result`. When not logging, `result` is set to -1.',
    snippet: 'loginfo ${1:strvar}',
  },
  {
    name: 'logrotate',
    signature: "logrotate 'size' '<size>'\nlogrotate 'rotate' <count>\nlogrotate 'halt'",
    description: 'Configures log rotation.',
    descriptionJa: 'ログローテーションの設定を行う',
  },
  {
    name: 'logautoclosemode',
    signature: 'logautoclosemode <flag>',
    description: 'When <flag> is 1, automatically closes the log file when the macro finishes.',
    descriptionJa: '<flag> の値が1の場合、マクロ終了時に自動的にログ採取を停止する',
    snippet: 'logautoclosemode ${1:1}',
  },
  // ── パスワード管理 ───────────────────────────────────────────────────────────
  {
    name: 'setpassword',
    signature: 'setpassword <filename> <password name> <password>',
    description: 'Stores an encrypted password in a password file.',
    descriptionJa: 'パスワードファイル <filename> にパスワードを暗号化して保存する',
    returnsJa: '`result` … パスワードファイルへの書き込みに失敗すると 0、それ以外は 1。',
    returns: '`result` … set to 0 if the password file cannot be written, 1 otherwise.',
  },
  {
    name: 'getpassword',
    signature: 'getpassword <filename> <password name> <password var>',
    description: 'Retrieves and decrypts a password from a password file.',
    descriptionJa: 'パスワードファイルからパスワードを読みだして復号化する',
    returnsJa: '復号したパスワードを `<password var>` に格納。`result` … パスワードファイルへの書き込みに失敗すると 0、それ以外は 1。*(バージョン 4.71 以降)*',
    returns: 'Stores the decrypted password in `<password var>`. `result` … set to 0 if the password file cannot be written, 1 otherwise. *(version 4.71 or later)*',
  },
  {
    name: 'delpassword',
    signature: 'delpassword <filename> <password name>',
    description: 'Deletes a password from a password file.',
    descriptionJa: 'パスワードファイルからパスワードを削除する',
  },
  {
    name: 'ispassword',
    signature: 'ispassword <filename> <password name>',
    description: 'Checks if a password exists in a password file.',
    descriptionJa: 'パスワードファイルにパスワードが存在するか調べる',
    returnsJa: '`result` … 指定したパスワードが設定されていれば 1、なければ 0。',
    returns: '`result` … set to 1 if the named password exists, 0 otherwise.',
  },
  {
    name: 'setpassword2',
    signature: 'setpassword2 <filename> <password name> <password> <encrypt str>',
    description: 'Stores a password encrypted with a user-provided key.',
    descriptionJa: 'ユーザー指定のキーで暗号化したパスワードをパスワードファイルに保存する',
    returnsJa: '`result` … パスワードファイルへの書き込みに失敗すると 0、それ以外は 1。',
    returns: '`result` … set to 0 if the password file cannot be written, 1 otherwise.',
  },
  {
    name: 'getpassword2',
    signature: 'getpassword2 <filename> <password name> <password var> <encrypt str>',
    description: 'Retrieves and decrypts a password using a user-provided key.',
    descriptionJa: 'ユーザー指定のキーでパスワードを復号化して取得する',
    returnsJa: '復号したパスワードを `<password var>` に格納。`result` … パスワードファイルへの書き込みに失敗すると 0、それ以外は 1。',
    returns: 'Stores the decrypted password in `<password var>`. `result` … set to 0 if the password file cannot be written, 1 otherwise.',
  },
  {
    name: 'delpassword2',
    signature: 'delpassword2 <filename> <password name>',
    description: 'Deletes a password from a password file created by setpassword2.',
    descriptionJa: 'setpassword2 で作成されたパスワードファイルからパスワードを削除する',
  },
  {
    name: 'ispassword2',
    signature: 'ispassword2 <filename> <password name>',
    description: 'Checks if a password created by setpassword2 exists.',
    descriptionJa: 'setpassword2 で作成されたパスワードファイルにパスワードが存在するか調べる',
    returnsJa: '`result` … 指定したパスワードが設定されていれば 1、なければ 0。',
    returns: '`result` … set to 1 if the named password exists, 0 otherwise.',
  },
  // ── ファイル転送プロトコル ───────────────────────────────────────────────────
  {
    name: 'bplusrecv',
    signature: 'bplusrecv',
    description: 'Receives a file from the host with the B-Plus protocol.',
    descriptionJa: 'B-Plus プロトコルでファイルを受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'bplussend',
    signature: 'bplussend <filename>',
    description: 'Sends a file to the host with the B-Plus protocol.',
    descriptionJa: 'ファイル <filename> を B-Plus プロトコルで送信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "bplussend '${1:filename}'",
  },
  {
    name: 'quickvanrecv',
    signature: 'quickvanrecv',
    description: 'Receives a file from the host with the Quick-VAN protocol.',
    descriptionJa: 'Quick-VAN プロトコルでファイルを受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'quickvansend',
    signature: 'quickvansend <filename>',
    description: 'Sends a file to the host with the Quick-VAN protocol.',
    descriptionJa: 'ファイル <filename> を Quick-VAN プロトコルで送信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "quickvansend '${1:filename}'",
  },
  {
    name: 'kmtrecv',
    signature: 'kmtrecv',
    description: 'Receives a file from the host with the Kermit protocol.',
    descriptionJa: 'Kermit プロトコルでファイルを受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'kmtsend',
    signature: 'kmtsend <filename>',
    description: 'Sends a file to the host with the Kermit protocol.',
    descriptionJa: 'ファイル <filename> を Kermit プロトコルで送信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "kmtsend '${1:filename}'",
  },
  {
    name: 'kmtget',
    signature: 'kmtget <filename>',
    description: 'Gets a file from the host using the Kermit Get command.',
    descriptionJa: 'ファイル <filename> を Kermit Get コマンドを使用してホストから受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "kmtget '${1:filename}'",
  },
  {
    name: 'kmtfinish',
    signature: 'kmtfinish',
    description: 'Pauses until the end of the Kermit Finish command.',
    descriptionJa: 'Kermit Finish コマンドが終了するまで次のコマンドは実行されない',
    returnsJa: '`result` … Finish コマンドが正しく実行された場合 1、それ以外 0。',
    returns: '`result` … set to 1 if the Finish command executes successfully, 0 otherwise.',
  },
  {
    name: 'xmodemrecv',
    signature: 'xmodemrecv <filename> <binary flag> <option>',
    description: 'Receives a file from the host with the XMODEM protocol.',
    descriptionJa: 'XMODEM プロトコルでファイル <filename> を受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'xmodemsend',
    signature: 'xmodemsend <filename> <option>',
    description: 'Sends a file to the host with the XMODEM protocol.',
    descriptionJa: 'XMODEM プロトコルでファイル <filename> を送信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "xmodemsend '${1:filename}' ${2:0}",
  },
  {
    name: 'ymodemrecv',
    signature: 'ymodemrecv',
    description: 'Receives a file from the host with the YMODEM protocol.',
    descriptionJa: 'YMODEM プロトコルでファイルを受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'ymodemsend',
    signature: 'ymodemsend <filename>',
    description: 'Sends a file to the host with the YMODEM protocol.',
    descriptionJa: 'ファイル <filename> を YMODEM プロトコルで送信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "ymodemsend '${1:filename}'",
  },
  {
    name: 'zmodemrecv',
    signature: 'zmodemrecv',
    description: 'Receives a file from the host with the ZMODEM protocol.',
    descriptionJa: 'ZMODEM プロトコルでファイルを受信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
  },
  {
    name: 'zmodemsend',
    signature: 'zmodemsend <filename> <binary flag>',
    description: 'Sends a file to the host with the ZMODEM protocol.',
    descriptionJa: 'ファイル <filename> を ZMODEM プロトコルで送信する',
    returnsJa: '`result` … 転送が成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on a successful transfer, 0 otherwise.',
    snippet: "zmodemsend '${1:filename}' ${2:0}",
  },
  {
    name: 'scprecv',
    signature: 'scprecv <remote filename> [<local filename>]',
    description: 'Receives a file from the host with the SCP protocol.',
    descriptionJa: 'ファイル <remote filename> を SCP プロトコルで受信する',
    snippet: "scprecv '${1:remote filename}'",
  },
  {
    name: 'scpsend',
    signature: 'scpsend <filename> [<destination filename>]',
    description: 'Sends a file to the host with the SCP protocol.',
    descriptionJa: 'ファイル <filename> を SCP プロトコルで送信する',
    snippet: "scpsend '${1:filename}'",
  },
  // ── シリアル通信設定 ─────────────────────────────────────────────────────────
  {
    name: 'setbaud',
    signature: 'setbaud <value>',
    description: 'Changes the baud rate of the serial port.',
    descriptionJa: 'シリアルポートのボーレートを <value> bps に変更する',
    snippet: 'setbaud ${1:9600}',
  },
  {
    name: 'setspeed',
    signature: 'setspeed <value>',
    description: 'Changes the speed of the serial port.',
    descriptionJa: 'シリアルポートのスピードを <value> bps に変更する',
    snippet: 'setspeed ${1:9600}',
  },
  {
    name: 'setflowctrl',
    signature: 'setflowctrl <value>',
    description: 'Changes the flow control setting.',
    descriptionJa: 'フロー制御の設定を変更する',
    snippet: 'setflowctrl ${1:0}',
  },
  {
    name: 'setdtr',
    signature: 'setdtr <flag>',
    description: 'Sets or clears the DTR signal. Only effective for serial connections with no flow control.',
    descriptionJa: '接続がシリアル接続でフロー制御が none の場合に DTR 信号を制御する',
    snippet: 'setdtr ${1:1}',
  },
  {
    name: 'setrts',
    signature: 'setrts <flag>',
    description: 'Sets or clears the RTS signal. Only effective for serial connections with no flow control.',
    descriptionJa: '接続がシリアル接続でフロー制御が none の場合に RTS 信号を制御する',
    snippet: 'setrts ${1:1}',
  },
  {
    name: 'setserialdelaychar',
    signature: 'setserialdelaychar <delay>',
    description: 'Changes the inter-character delay for serial transmission in milliseconds.',
    descriptionJa: 'シリアルポートの送信待ち時間（1文字ごと）を <delay> [ms] に変更する',
    snippet: 'setserialdelaychar ${1:10}',
  },
  {
    name: 'setserialdelayline',
    signature: 'setserialdelayline <delay>',
    description: 'Changes the inter-line delay for serial transmission in milliseconds.',
    descriptionJa: 'シリアルポートの送信待ち時間（1行ごと）を <delay> [ms] に変更する',
    snippet: 'setserialdelayline ${1:100}',
  },
  // ── その他通信設定 ───────────────────────────────────────────────────────────
  {
    name: 'setsync',
    signature: 'setsync <sync flag>',
    description: 'Enters synchronous communication mode if <sync flag> is non-zero.',
    descriptionJa: '<sync flag> が0以外ならば同期通信モードに入る',
    snippet: 'setsync ${1:1}',
  },
  {
    name: 'setecho',
    signature: 'setecho <echo flag>',
    description: 'Turns local echo on (non-zero) or off (zero).',
    descriptionJa: '<echo flag> が0以外ならローカルエコーは on になる',
    snippet: 'setecho ${1:1}',
  },
  {
    name: 'enablekeyb',
    signature: 'enablekeyb <flag>',
    description: 'Enables (1) or disables (0) keyboard input.',
    descriptionJa: '<flag> の値が1の場合は許可、0の場合はキーボード入力を禁止する',
    snippet: 'enablekeyb ${1:1}',
  },
  {
    name: 'setmulticastname',
    signature: 'setmulticastname <multicastname>',
    description: 'Sets the multicast name of this terminal.',
    descriptionJa: '自身の端末に対して <multicastname> を識別子として設定する',
    snippet: "setmulticastname '${1:name}'",
  },
  // ── その他 ───────────────────────────────────────────────────────────────────
  {
    name: 'include',
    signature: "include '<include file name>'",
    description: 'Loads and executes the specified macro file.',
    descriptionJa: '引数に指定したマクロファイルを読み込み、マクロ実行を行う',
    snippet: "include '${1:filename.ttl}'",
  },
  {
    name: 'ifdefined',
    signature: 'ifdefined <var>',
    description: 'Sets "result" to the type of <var>: 0=undefined, 1=integer, 2=string, 3=int array, 4=string array.',
    descriptionJa: '<var> の型を表す値をシステム変数 result に格納する',
    returnsJa: '`result` … 0=未定義, 1=整数, 3=文字列, 4=ラベル, 5=整数配列, 6=文字列配列。',
    returns: '`result` … 0=undefined, 1=integer, 3=string, 4=label, 5=integer array, 6=string array.',
    snippet: 'ifdefined ${1:var}',
  },
  {
    name: 'exec',
    signature: 'exec <command line> [<show> [<wait> [<current directory>]]]',
    description: 'Runs an application specified by the command line.',
    descriptionJa: 'コマンドライン文字列 <command line> に従い、アプリケーションを起動する',
    returnsJa: '`result` … **4.103 以降:** `<wait>` が 1 なら -1=実行失敗/それ以外=終了コード。`<wait>` が 1 以外なら -1=失敗/0=成功。**4.63–4.102:** `<wait>` が 1 のときのみ終了コードを格納（失敗判定なし）。',
    returns: '`result` … **4.103 or later:** if `<wait>` is 1: -1=failed / otherwise exit code. If `<wait>` is not 1: -1=failed / 0=success. **4.63–4.102:** if `<wait>` is 1, only the exit code is stored (no failure indicator).',
    snippet: "exec '${1:command}'",
  },
  {
    name: 'execcmnd',
    signature: 'execcmnd <statement>',
    description: 'Executes a TTL statement expressed by the string <statement>.',
    descriptionJa: '文字列 <statement> が表現する TTL コマンドを実行する',
    snippet: "execcmnd '${1:sendln \"hello\"}'",
  },
  {
    name: 'callmenu',
    signature: 'callmenu <menu ID>',
    description: 'Executes the menu item specified by <menu ID>.',
    descriptionJa: '<menu ID> で指定されたメニューを実行する',
    snippet: 'callmenu ${1:50280}',
  },
  {
    name: 'loadkeymap',
    signature: 'loadkeymap <filename>',
    description: 'Causes Tera Term to load a keyboard setup file.',
    descriptionJa: 'キーボード設定ファイル <filename> を Tera Term に読み込ませる',
    snippet: "loadkeymap '${1:keyboard.cnf}'",
  },
  {
    name: 'restoresetup',
    signature: 'restoresetup <filename>',
    description: 'Causes Tera Term to load a setup file.',
    descriptionJa: 'Tera Term 設定ファイル <filename> を Tera Term に読み込ませる',
    snippet: "restoresetup '${1:teraterm.ini}'",
  },
  {
    name: 'setdebug',
    signature: 'setdebug <flag>',
    description: 'Sets the debug flag of Tera Term.',
    descriptionJa: 'Tera Term のデバッグモードを設定する',
    snippet: 'setdebug ${1:1}',
  },
  {
    name: 'setexitcode',
    signature: 'setexitcode <exit code>',
    description: 'Sets the exit code of MACRO.',
    descriptionJa: 'MACRO の終了コードを設定する',
    snippet: 'setexitcode ${1:0}',
  },
  {
    name: 'setfileattr',
    signature: 'setfileattr <filename> <attributes>',
    description: 'Sets the file attributes.',
    descriptionJa: 'ファイルの属性を設定する',
    returnsJa: '`result` … 変更に成功すると 1、失敗すると 0。',
    returns: '`result` … set to 1 on success, 0 on failure.',
  },
  {
    name: 'getfileattr',
    signature: 'getfileattr <filename>',
    description: 'Gets the file attributes. Stores the result in "result".',
    descriptionJa: 'ファイルの属性を取得する',
    returnsJa: '`result` … 取得失敗で -1、成功で属性値（$1 読取専用・$2 隠し・$10 ディレクトリ・$20 アーカイブ などの組み合わせ）。',
    returns: '`result` … -1 on failure, otherwise the attribute bitmask ($1 read-only, $2 hidden, $10 directory, $20 archive, etc.).',
    snippet: "getfileattr '${1:filename}'",
  },
  {
    name: 'clipb2var',
    signature: 'clipb2var <strvar> [<offset>]',
    description: 'Copies text data from clipboard to <strvar>.',
    descriptionJa: 'クリップボードのテキストデータを <strvar> へ代入する',
    returnsJa: 'クリップボードのテキストを `<strvar>` に代入。`result` … 0=クリップボードを開けない/テキストでない/offset 不正, 1=代入成功, 2=代入したが切り捨てあり, 3=メモリ確保失敗。',
    returns: 'Stores the clipboard text in `<strvar>`. `result` … 0=cannot open clipboard / not text / bad offset, 1=stored, 2=stored but truncated, 3=memory allocation failed.',
    snippet: 'clipb2var ${1:strvar}',
  },
  {
    name: 'var2clipb',
    signature: 'var2clipb <string>',
    description: 'Copies <string> to the clipboard.',
    descriptionJa: '<string> をクリップボードにコピーする',
    returnsJa: '`result` … クリップボードへのコピーに成功すると 1、開けないと 0。',
    returns: '`result` … set to 1 when copied to the clipboard, 0 if it cannot be opened.',
    snippet: 'var2clipb ${1:string}',
  },
] satisfies ReadonlyArray<TtlCommand>;

/**
 * コマンド名（小文字）からコマンド定義への参照マップ
 *
 * @remarks 補完・ホバーでの高速参照に使用
 */
export const TTL_COMMANDS_MAP: ReadonlyMap<string, TtlCommand> = new Map(
  TTL_COMMANDS.map(command => [command.name.toLowerCase(), command])
);

/**
 * 制御フロー構造キーワード
 *
 * @remarks コマンドデータがない純粋な構文キーワード
 */
export const TTL_STRUCTURAL_KEYWORDS = [
  'if', 'then', 'else', 'elseif', 'endif',
  'for', 'next',
  'while', 'endwhile',
  'do', 'loop',
  'until', 'enduntil',
  'break', 'continue',
  'call', 'return',
  'end', 'goto',
] as const satisfies ReadonlyArray<string>;

/**
 * システム変数
 *
 * @remarks コマンド実行結果や入力値を保持する定義済み変数
 */
export const TTL_SYSTEM_VARIABLES = [
  'result',
  'inputstr',
  'matchstr',
  'groupmatchstr1', 'groupmatchstr2', 'groupmatchstr3',
  'groupmatchstr4', 'groupmatchstr5', 'groupmatchstr6',
  'groupmatchstr7', 'groupmatchstr8', 'groupmatchstr9',
  'param1', 'param2', 'param3', 'param4', 'param5',
  'param6', 'param7', 'param8', 'param9',
  'params', 'paramcnt',
  'timeout', 'mtimeout',
] as const satisfies ReadonlyArray<string>;

/**
 * ドキュメントヘッダ用スニペット一覧
 *
 * @remarks
 * `///` 入力で補完候補に並ぶ。行頭（ファイル/関数の大きなヘッダ）と
 * 行中（セクション区切り）の 2 種類を提供する。
 */
export const TTL_DOC_HEADER_SNIPPETS = [
  {
    label: '/// ドキュメントヘッダ (行頭)',
    detail: 'TTL doc header block',
    documentation: '概要・説明・前提条件・必須変数/生成変数の表を含む定型ヘッダを挿入します。',
    body: [
      '; ==================================================',
      '; ${1:概要}',
      ';',
      '; ${2:説明}',
      ';',
      '; 前提条件:',
      ';   - ${3:なにか}',
      ';',
      '; 必須変数:',
      '; | 変数名 | R/W | 概要 |',
      '; | ------ | :-: | ---- |',
      '; |        |     |      |',
      ';',
      '; 生成変数:',
      '; | 変数名 | R/W | 概要 |',
      '; | ------ | :-: | ---- |',
      '; |        |     |      |',
      ';',
      '; ==================================================',
      '$0',
    ].join('\n'),
  },
  {
    label: '/// セクション区切り (行中)',
    detail: 'TTL section divider',
    documentation: '短いセクション区切りコメントを挿入します。',
    body: [
      '; -------------------',
      '; ${1:概要}',
      '; -------------------',
      '$0',
    ].join('\n'),
  },
] as const satisfies ReadonlyArray<TtlDocHeaderSnippet>;
